### ISSUE TITLE
`ueye_cam` package for NEXTAGE OPEN

### ISSUE THREAD

**Issue by youtalk** [tork-a/rtmros_nextage#103]
Sorry, it's not directly for the `rtmros_nextage` issue but just notice to you.
Recently I'm trying to develop a camera package for NEXTAGE OPEN by forking [anqixu/ueye_cam](https://github.com/anqixu/ueye_cam).

https://github.com/youtalk/ueye_cam (`nextage-cams` branch by default)

I succeeded in capturing 4 cameras at a time but there are known issues.
- Cannot use bgr8 color mode (only mono8 mode can be used). We need to convert bgr8 to ROS compatible rgb8 with `cv_bridge`.
- Cannot remove `image_width` and `image_height` params in launch files. `ueye_cam` updates 640 x 480 by default if there are no params in them.

I only added some launch files so far. To resolve them we need to modify `ueye_cam` source codes.
Do you already have some plan to make a camera package? If not, please consider to help me.

**Comment by 130s** [comment]
> Do you already have some plan to make a camera package?

So far we have better touch with [ueye](http://wiki.ros.org/ueye) package, not `ueye_cam`. [We've added a change to its upstream](https://bitbucket.org/kmhallen/ueye/pull-request/5/use-arg-to-change-parameters/diff). But this doesn't mean `ueye` package should be used for nxo, since we aren't that certain what's the best option.

With the PReq above, we got VGA 30 FPS.

```
$ roslaunch ueye nodelets.launch zoom:=4 auto_exposure:=true auto_gain:=true
```

For stereo the following was good:

```
<launch>
  <node pkg="nodelet" type="nodelet" name="nodelet_manager" args="manager" output="screen" />

  <node pkg="nodelet" type="nodelet" name="ueye_cam_nodelet_master"
        args="load ueye_cam/ueye_cam_nodelet nodelet_manager">
    <param name="camera_name" type="str" value="master" /> <!-- == namespace for topics and services -->
    <param name="camera_topic" type="str" value="image_raw" />
    <param name="camera_id" type="int" value="1" /> <!-- 0 = any camera; 1+: camera ID -->
    <param name="camera_intrinsics_file" type="string" value="" /> <!-- default: ~/.ros/camera_info/<camera_name>.yaml -->
    <param name="camera_parameters_file" type="string" value="" /> <!-- default: ~/.ros/camera_conf/<camera_name>.ini -->

    <param name="ext_trigger_mode" type="bool" value="False" /> <!-- if False, then camera will operate in free-run mode; otherwise, frames need to be triggered by hardware signal (falling-edge) on digital input pin of camera -->

    <!-- the following are optional camera configuration parameters:
         they will be loaded on the camera after the .ini configuration
         file, and before dynamic_reconfigure. That means that any
         (lingering) dynamic parameters from dynamic_reconfigure will
         override these values, and that these will override parameters
         from the .ini file.
         See http://www.ros.org/wiki/ueye_cam for more details. -->

    <param name="color_mode" type="str" value="rgb8" /> <!-- valid options: 'rgb8', 'mono8', 'bayer_rggb8' -->

    <!-- WARNING: the following 4 parameters specify dimensions for camera's area of interest. Values for image_width and image_height that are smaller than your camera's maximum values will result in cropped field of view. For typical cases, one should modify values for sensor_scaling / binning / subsampling to downsample the resulting ROS image to the desired dimensions, without losing potential field of view. -->
    <param name="image_width" type="int" value="2560" />
    <param name="image_height" type="int" value="1920" />
    <param name="image_top" type="int" value="-1" /> <!-- -1: center -->
    <param name="image_left" type="int" value="-1" /> <!-- -1: center -->

    <param name="subsampling" type="int" value="1" /> <!-- supported by only some UEye cameras -->
    <param name="binning" type="int" value="4" /> <!-- supported by only some UEye cameras -->
    <param name="sensor_scaling" type="double" value="1.0" /> <!-- supported by only some UEye cameras -->

    <param name="auto_gain" type="bool" value="True" />
    <param name="master_gain" type="int" value="0" />
    <param name="red_gain" type="int" value="0" />
    <param name="green_gain" type="int" value="1" />
    <param name="blue_gain" type="int" value="16" />
    <param name="gain_boost" type="bool" value="False" />

    <param name="auto_exposure" type="bool" value="False" />
    <param name="exposure" type="int" value="33" /> <!-- in ms -->

    <param name="auto_white_balance" type="bool" value="True" />
    <param name="white_balance_red_offset" type="int" value="0" />
    <param name="white_balance_blue_offset" type="int" value="0" />

    <param name="flash_delay" type="int" value="30000" /> <!-- in us -->
    <param name="flash_duration" type="int" value="1000" /> <!-- in us -->

    <param name="auto_frame_rate" type="bool" value="False" />
    <param name="frame_rate" type="double" value="15.0" />
    <param name="pixel_clock" type="int" value="30" />
  </node>

  <node pkg="nodelet" type="nodelet" name="ueye_cam_nodelet_slave1"
        args="load ueye_cam/ueye_cam_nodelet nodelet_manager">
    <param name="camera_name" type="str" value="slave1" /> <!-- == namespace for topics and services -->
    <param name="camera_topic" type="str" value="image_raw" />
    <param name="camera_id" type="int" value="2" /> <!-- 0 = any camera; 1+: camera ID -->
    <param name="camera_intrinsics_file" type="string" value="" /> <!-- default: ~/.ros/camera_info/<camera_name>.yaml -->
    <param name="camera_parameters_file" type="string" value="" /> <!-- default: ~/.ros/camera_conf/<camera_name>.ini -->

    <param name="ext_trigger_mode" type="bool" value="False" /> <!-- if False, then camera will operate in free-run mode; otherwise, frames need to be triggered by hardware signal (falling-edge) on digital input pin of camera -->

    <!-- the following are optional camera configuration parameters:
         they will be loaded on the camera after the .ini configuration
         file, and before dynamic_reconfigure. That means that any
         (lingering) dynamic parameters from dynamic_reconfigure will
         override these values, and that these will override parameters
         from the .ini file.
         See http://www.ros.org/wiki/ueye_cam for more details. -->

    <param name="color_mode" type="str" value="rgb8" /> <!-- valid options: 'rgb8', 'mono8', 'bayer_rggb8' -->

    <param name="image_width" type="int" value="2560" />
    <param name="image_height" type="int" value="1920" />
    <param name="image_top" type="int" value="-1" /> <!-- -1: center -->
    <param name="image_left" type="int" value="-1" /> <!-- -1: center -->

    <param name="subsampling" type="int" value="1" /> <!-- supported by only some UEye cameras -->
    <param name="binning" type="int" value="4" /> <!-- supported by only some UEye cameras -->
    <param name="sensor_scaling" type="double" value="1.0" /> <!-- supported by only some UEye cameras -->

    <param name="auto_gain" type="bool" value="True" />
    <param name="master_gain" type="int" value="0" />
    <param name="red_gain" type="int" value="0" />
    <param name="green_gain" type="int" value="1" />
    <param name="blue_gain" type="int" value="16" />
    <param name="gain_boost" type="bool" value="False" />

    <param name="auto_exposure" type="bool" value="False" />
    <param name="exposure" type="int" value="33" /> <!-- in ms -->

    <param name="auto_white_balance" type="bool" value="True" />
    <param name="white_balance_red_offset" type="int" value="0" />
    <param name="white_balance_blue_offset" type="int" value="0" />

    <param name="flash_delay" type="int" value="0" /> <!-- in us -->
    <param name="flash_duration" type="int" value="1000" /> <!-- in us -->

    <param name="auto_frame_rate" type="bool" value="False" /> <!-- frame rate settings are ignored in camera_ext_trigger_mode -->
    <param name="frame_rate" type="double" value="15.0" /> <!-- frame rate settings are ignored in camera_ext_trigger_mode -->
    <param name="pixel_clock" type="int" value="30" />
  </node>

</launch>
```

Notice:
- On real robot `ext_trigger_mode` might have to be `true`
- 15 FPS is maximum? since we used USB2.0. Setting `frame_rate` as 30 didn't work out.

For usb_cam this diff was necessary:

```
ueye_cam$ git diff
diff --git a/launch/rgb8.launch b/launch/rgb8.launch
index 4ee006d..cf8cd22 100644
--- a/launch/rgb8.launch
+++ b/launch/rgb8.launch
@@ -22,13 +22,13 @@
     <param name="color_mode" type="str" value="rgb8" /> <!-- valid options: 'rgb8', 'mono8', 'bayer_rggb8' -->

     <!-- WARNING: the following 4 parameters specify dimensions for camera's area of interest. Values for image_width and image_height that are smaller than your camera's maximum values will result in cropped field of view. For typical cases, one should modify values for sensor_scaling / binning / subsampling to downsample the resulting ROS image to the desired dimensions, without losing potential field of view. -->
-    <param name="image_width" type="int" value="640" />
-    <param name="image_height" type="int" value="480" />
+    <param name="image_width" type="int" value="2560" />
+    <param name="image_height" type="int" value="1920" />
     <param name="image_top" type="int" value="-1" /> <!-- -1: center -->
     <param name="image_left" type="int" value="-1" /> <!-- -1: center -->

     <param name="subsampling" type="int" value="1" /> <!-- supported by only some UEye cameras -->
-    <param name="binning" type="int" value="1" /> <!-- supported by only some UEye cameras -->
+    <param name="binning" type="int" value="4" /> <!-- supported by only some UEye cameras -->
     <param name="sensor_scaling" type="double" value="1.0" /> <!-- supported by only some UEye cameras -->

     <param name="auto_gain" type="bool" value="True" />
@@ -50,6 +50,6 @@

     <param name="auto_frame_rate" type="bool" value="False" />
     <param name="frame_rate" type="double" value="30.0" />
-    <param name="pixel_clock" type="int" value="25" />
+    <param name="pixel_clock" type="int" value="70" />
   </node>
 </launch>
```

**Comment by youtalk** [comment]
@130s Oh, I'm sorry but I didn't know about the `ueye` package and issue #5 
I'll check the package. Thank you.

**Comment by k-okada** [comment]
@youtalk, BTW how do you synchronize two stereo camera?  It seems the camera accept external trigger and this is the reason that you choose this camera, and I think following parameter is designed for this purpose.

```
+   <arg name="trigger"     default="0" /> <!-- 0:AUTO, 1:HARDWARE_RISING, 2:HARDWARE_FALLING -->
```

**Comment by youtalk** [comment]
@k-okada Unfortunately NEXTAGE has no external trigger as you may know. So when I calibrate stereo camera, I add `--approximate=0.1` and `_approximate_sync:=True` option to rosrun command.

For example: 

```
$ rosrun camera_calibration cameracalibrator.py --size 9x6 --square 0.024 --approximate=0.1 right:=/stereo/right/image_raw left:=/stereo/left/image_raw right_camera:=/stereo/right left_camera:=/stereo/left
$ rosrun image_view stereo_view stereo:=/stereo image:=image_rect _approximate_sync:=True _queue_size:=10
```

But I checked the [online manual of uEye camera](http://www.cihansari.com/vistek/uEye_Manual/index.html?hw_triggermodus.html) in detail and found `software trigger mode`. I'll check the NEXTAGE's stereo camera can be enabled or not.

**Comment by k-okada** [comment]
> So when I calibrate stereo camera, I add --approximate=0.1 option to 
> rosrun command.

That's good to know. Thanks

**Comment by longjie** [comment]
Hi, all.

I'm trying to calibrate our NEXTAGE OPEN's stereo camera.
Using ueye_cam package as @youtalk mentioned, I got a bit low frame rate (10Hz) but no problem to accquire images.
On the other hand using ueye package, I got 13Hz frame rate. But I got error while cameracaliblater.py running.

```
[ERROR] [1410362776.402743825]: Failed to acquire image from UEye camera 'master' (IS_TIMED_OUT)
```

I used launch file which @130s provided in this issue. And I used calibration command as follow:

```
$ rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.024 --approximate=0.1 right:=/master/image_raw left:=/slave1/image_raw right_camera:=/master left_camera:=/slave1
```

Don't you have same situation?

**Comment by k-okada** [comment]
Sorry for late reply.

Which camera are you using? we're using UI-1480SE-C-HQ and sometimes it fail to acquire image when launch capture node, but once it is running, usually it is ok.

If you're using different camera, we have to change the launch file.

**Comment by longjie** [comment]
Hi, 
Our NEXTAGE Open has the cameras as follows:
Head stereo camera  IDS:UI-1550SE-C-HQ
Hand camera　IDS:UI-1220LE-C-HQ
I'm going to check the launch file later. Thanks.

**Comment by k-okada** [comment]
Hum that's strange, the camera we're using is borrowed from manufacturer and we believed that is the same one as you have in your robot head, but that was mistake.

So, please check default parameter for your camera
1) run ueyedemo push start button (open a uEye)
2) choose uEye->Properties->Size
3) select appropriate size by changing binning of size tab (800x600?)
4) choose uEye-> reset to defaults
5) choose uEye->Properties->Camera check pixelclock framerate and exposure value

**Comment by youtalk** [comment]
After some trials, `ueye` package seems to be better than `ueye_cam`.
The `zoom` parameter works well to rapidly capture head cameras.

By the way, how can I change `cameraId` in launch file or terminal command?
https://bitbucket.org/kmhallen/ueye/src/9aef2efdafdab29e3cdf0dae49705e1c90dc89f2/src/CameraNode.cpp?at=default#cl-95
I'm sorry but I'm not sure about `private node handle`.

**Comment by k-okada** [comment]
use param tag, 
        <node pkg="nodelet" type="nodelet" name="camera_nodelet" args="load 
ueye/CameraNodelet ueye_manager">
                <param name="cameraId" value="2" />
        </node>

it seems default nodlets.launch did not support cameraId, so we'd better to 
create patch and send pull request as I did before.
https://bitbucket.org/kmhallen/ueye/pull-request/5/use-arg-to-change-parameters/diff

**Comment by k-okada** [comment]
here is screen shot for instruction described in https://github.com/tork-a/rtmros_nextage/issues/103#issuecomment-55370979

![size](https://cloud.githubusercontent.com/assets/493276/4251444/8812e374-3a8d-11e4-9bce-5db5936126a3.png)
![camera](https://cloud.githubusercontent.com/assets/493276/4251465/8e0d9ca6-3a8d-11e4-93fa-bfbb3375b1f6.png)

**Comment by youtalk** [comment]
@k-okada Oh, that's right. I'll create the patch.
Thank you for your help.

**Comment by longjie** [comment]
Hi,

> So, please check default parameter for your camera
> 1) run ueyedemo push start button (open a uEye)
> 2) choose uEye->Properties->Size

Default image size is 1600x1200. It is being captured in 10 FPS.

![screenshot from 2014-09-16 18 02 38](https://cloud.githubusercontent.com/assets/238460/4284986/d28c3eb8-3d81-11e4-9c95-642a822ba695.png)

> 3) select appropriate size by changing binning of size tab (800x600?)

Should I change the binning size to 2x? It makes the image size to be 800x600 and it is captured in 28.59 FPS.

![screenshot from 2014-09-16 18 03 29](https://cloud.githubusercontent.com/assets/238460/4285014/e7ebc706-3d81-11e4-80f7-38d88175ff63.png)

> 4) choose uEye-> reset to defaults
> 5) choose uEye->Properties->Camera check pixelclock framerate and exposure value

When I reset it to defaults, the image size becomes 1600x1200. Pixelclock is 24 and framerate is 10.

![screenshot from 2014-09-16 18 07 46](https://cloud.githubusercontent.com/assets/238460/4285022/f3877376-3d81-11e4-89e8-4f6e00d7ce9e.png)

So, I guess I should set appropriate parameters as follows:

```
    <param name="image_width" type="int" value="1600" />
    <param name="image_height" type="int" value="1200" />
    <param name="binning" type="int" value="2" /> <!-- supported by only some UEye cameras -->
   <param name="frame_rate" type="double" value="30.0" />
    <param name="pixel_clock" type="int" value="24" />
```

I get no errors by these parameters. It runs 30 FPS and I can do stereo calibration. Thank you!

**Comment by youtalk** [comment]
With my PR for [ueye](https://bitbucket.org/kmhallen/ueye) (not `ueye_cam`) I also succeeded in capturing stereo camera in 30 FPS.

https://bitbucket.org/kmhallen/ueye/pull-request/6/add-camera_id-argument-to-change-camera/diff

```
$ ROS_NAMESPACE=left roslaunch ueye nodelets.launch camera_id:=1 zoom:=2 auto_exposure:=true auto_gain:=true
$ ROS_NAMESPACE=right roslaunch ueye nodelets.launch camera_id:=2 zoom:=2 auto_exposure:=true auto_gain:=true
```

However I think using [StereoCamera](https://bitbucket.org/kmhallen/ueye/src/c4e4612559ae4625a5908c7fa638d384e25324be/src/StereoNode.cpp?at=default) is better.

**Comment by k-okada** [comment]
Thanks @longjie @youtalk, I have created small tutorial [1] and want to create `nextage_ueye_stereo.launch` file. From @longie 's report I create ueye_cam version of this and 
if ueye version of stereo is robust and fast then ueye_cam, then we'd better to select them. Unfortunately we do not have stereo head for nextage robot, so hope @youtalk confirm both of them.

note: I need some trouble on ueye_cam stereo settings, hope this help to work on ueye package
- ueye_cam driver automatically start/stop capturing the data and we need to run rostopic in launch file to keep capturing the data. image_proc did not subscribe image_raw(input of image_proc) unless someone subscribe image_rect_color (output of image_proc), but even we subscribe image_rect_color, ueye_cam did not start capturing the image
- somehow stereo_image_proc.launch did not work, because of missing approximation? https://github.com/ros-perception/image_pipeline/blob/indigo/stereo_image_proc/launch/stereo_image_proc.launch#L8

[1] http://wiki.ros.org/rtmros_nextage/Tutorials/Setup%20stereo%20camera
[2]

```
<launch>
  <node pkg="nodelet" type="nodelet" name="nodelet_manager" args="manager" output="screen" />

  <node pkg="nodelet" type="nodelet" name="ueye_cam_nodelet_master"
        args="load ueye_cam/ueye_cam_nodelet nodelet_manager">
    <param name="camera_name" type="str" value="right" /> <!-- == namespace for topics and services -->
    <param name="camera_topic" type="str" value="image_raw" />
    <param name="camera_id" type="int" value="1" /> <!-- 0 = any camera; 1+: camera ID -->
    <param name="camera_intrinsics_file" type="string" value="" /> <!-- default: ~/.ros/camera_info/<camera_name>.yaml -->
    <param name="camera_parameters_file" type="string" value="" /> <!-- default: ~/.ros/camera_conf/<camera_name>.ini -->

    <param name="ext_trigger_mode" type="bool" value="False" /> <!-- if False, then camera will operate in free-run mode; otherwise, frames need to be triggered by hardware signal (falling-edge) on digital input pin of camera -->

    <!-- the following are optional camera configuration parameters:
         they will be loaded on the camera after the .ini configuration
         file, and before dynamic_reconfigure. That means that any
         (lingering) dynamic parameters from dynamic_reconfigure will
         override these values, and that these will override parameters
         from the .ini file.
         See http://www.ros.org/wiki/ueye_cam for more details. -->

    <param name="color_mode" type="str" value="rgb8" /> <!-- valid options: 'rgb8', 'mono8', 'bayer_rggb8' -->

    <!-- WARNING: the following 4 parameters specify dimensions for camera's area of interest. Values for image_width and image_height that are smaller than your camera's maximum values will result in cropped field of view. For typical cases, one should modify values for sensor_scaling / binning / subsampling to downsample the resulting ROS image to the desired dimensions, without losing potential field of view. -->
    <param name="image_width" type="int" value="1600" />
    <param name="image_height" type="int" value="1200" />
    <param name="image_top" type="int" value="-1" /> <!-- -1: center -->
    <param name="image_left" type="int" value="-1" /> <!-- -1: center -->

    <param name="subsampling" type="int" value="1" /> <!-- supported by only some UEye cameras -->
    <param name="binning" type="int" value="2" /> <!-- supported by only some UEye cameras -->
    <param name="sensor_scaling" type="double" value="1.0" /> <!-- supported by only some UEye cameras -->

    <param name="auto_gain" type="bool" value="True" />
    <param name="master_gain" type="int" value="0" />
    <param name="red_gain" type="int" value="0" />
    <param name="green_gain" type="int" value="1" />
    <param name="blue_gain" type="int" value="16" />
    <param name="gain_boost" type="bool" value="False" />

    <param name="auto_exposure" type="bool" value="False" />
    <param name="exposure" type="int" value="33" /> <!-- in ms -->

    <param name="auto_white_balance" type="bool" value="True" />
    <param name="white_balance_red_offset" type="int" value="0" />
    <param name="white_balance_blue_offset" type="int" value="0" />

    <param name="flash_delay" type="int" value="30000" /> <!-- in us -->
    <param name="flash_duration" type="int" value="1000" /> <!-- in us -->

    <param name="auto_frame_rate" type="bool" value="False" />
    <param name="frame_rate" type="double" value="30.0" />
    <param name="pixel_clock" type="int" value="24" />
  </node>

  <node pkg="nodelet" type="nodelet" name="ueye_cam_nodelet_slave1"
        args="load ueye_cam/ueye_cam_nodelet nodelet_manager">
    <param name="camera_name" type="str" value="left" /> <!-- == namespace for topics and services -->
    <param name="camera_topic" type="str" value="image_raw" />
    <param name="camera_id" type="int" value="2" /> <!-- 0 = any camera; 1+: camera ID -->
    <param name="camera_intrinsics_file" type="string" value="" /> <!-- default: ~/.ros/camera_info/<camera_name>.yaml -->
    <param name="camera_parameters_file" type="string" value="" /> <!-- default: ~/.ros/camera_conf/<camera_name>.ini -->

    <param name="ext_trigger_mode" type="bool" value="False" /> <!-- if False, then camera will operate in free-run mode; otherwise, frames need to be triggered by hardware signal (falling-edge) on digital input pin of camera -->

    <!-- the following are optional camera configuration parameters:
         they will be loaded on the camera after the .ini configuration
         file, and before dynamic_reconfigure. That means that any
         (lingering) dynamic parameters from dynamic_reconfigure will
         override these values, and that these will override parameters
         from the .ini file.
         See http://www.ros.org/wiki/ueye_cam for more details. -->

    <param name="color_mode" type="str" value="rgb8" /> <!-- valid options: 'rgb8', 'mono8', 'bayer_rggb8' -->

    <param name="image_width" type="int" value="1600" />
    <param name="image_height" type="int" value="1200" />
    <param name="image_top" type="int" value="-1" /> <!-- -1: center -->
    <param name="image_left" type="int" value="-1" /> <!-- -1: center -->

    <param name="subsampling" type="int" value="1" /> <!-- supported by only some UEye cameras -->
    <param name="binning" type="int" value="2" /> <!-- supported by only some UEye cameras -->
    <param name="sensor_scaling" type="double" value="1.0" /> <!-- supported by only some UEye cameras -->

    <param name="auto_gain" type="bool" value="True" />
    <param name="master_gain" type="int" value="0" />
    <param name="red_gain" type="int" value="0" />
    <param name="green_gain" type="int" value="1" />
    <param name="blue_gain" type="int" value="16" />
    <param name="gain_boost" type="bool" value="False" />

    <param name="auto_exposure" type="bool" value="False" />
    <param name="exposure" type="int" value="33" /> <!-- in ms -->

    <param name="auto_white_balance" type="bool" value="True" />
    <param name="white_balance_red_offset" type="int" value="0" />
    <param name="white_balance_blue_offset" type="int" value="0" />

    <param name="flash_delay" type="int" value="0" /> <!-- in us -->
    <param name="flash_duration" type="int" value="1000" /> <!-- in us -->

    <param name="auto_frame_rate" type="bool" value="False" /> <!-- frame rate settings are ignored in camera_ext_trigger_mode -->
    <param name="frame_rate" type="double" value="30.0" /> <!-- frame rate settings are ignored in camera_ext_trigger_mode -->
    <param name="pixel_clock" type="int" value="24" />
  </node>

  <!-- force subscribe image raw to publish data -->
  <node pkg="rostopic" type="rostopic" name="left_force_subscribe" args="hz /left/camera_info" output="screen" />
  <node pkg="rostopic" type="rostopic" name="right_force_subscribe" args="hz /right/camera_info" output="screen"/>

  <!-- nodelet version of stereo_image_proc wont work???
  <include file='$(find stereo_image_proc)/launch/stereo_image_proc.launch' >
    <arg name="manager" value="/nodelet_manager" />
  </include>
  -->

  <node pkg="image_proc" type="image_proc" name="image_proc" ns="right"/>
  <node pkg="image_proc" type="image_proc" name="image_proc" ns="left"/>
  <node pkg="stereo_image_proc" type="stereo_image_proc"
        name="stereo_image_proc" args="_approximate_sync:=True" />

</launch>
```

**Comment by k-okada** [comment]
I added launch file to here -> https://github.com/tork-a/rtmros_nextage/pull/109, feel free to change this.
next procedure is to calibrate hand-eye coordinates, the package will be available within a few weeks,  see https://github.com/ros-perception/calibration/pull/31 for progress.

**Comment by youtalk** [comment]
@k-okada Thank you for your effort. I'll take it. Please wait few days.

**Comment by 130s** [comment]
Meanwhile, @k-okada [added a launch file for this](https://github.com/tork-a/rtmros_nextage/pull/109) and a [wiki tutorial](http://wiki.ros.org/rtmros_nextage/Tutorials/Setup%20stereo%20camera). Hope anyone who's giving a try adds updates to the wiki if necessary (I won't have an access to the camera h/w for awhile so I can't).

**Comment by youtalk** [comment]
Sorry for late reply. I tried to capture stereo with `ueye_cam` and `ueye`. While `ueye_cam` can be captured at 29 fps intervals, `ueye` can be captured at only 10 fps intervals at most. Although single camera capture is about the same speed, stereo capture by `ueye` happens something bad. It may be improved using [StereoCamera](https://bitbucket.org/kmhallen/ueye/src/c4e4612559ae4625a5908c7fa638d384e25324be/src/StereoNode.cpp?).

Anyway I've now concluded we should use `ueye_cam`.

**Comment by k-okada** [comment]
can we close this issue?

**Comment by youtalk** [comment]
Yes, thank you all.

**Comment by k-okada** [comment]
> next procedure is to calibrate hand-eye coordinates, the package will be available within a few weeks, see ros-perception/calibration#31 for progress.

As I told before, I created calibration package (https://github.com/start-jsk/rtmros_hironx/pull/251) and created tutorial (http://wiki.ros.org/rtmros_nextage/Tutorials/CalibrateKinect). I have tested on our hiro robot that equipped xiton sensors on the head, but not tested on stereo cam and may be we need to update setup script....

BTW do you plan to switch to use xtion for nextage head? that very easy to start.

**Comment by youtalk** [comment]
@k-okada Super cool package! Hope to test on stereo camera too.

We are sorry but we don't have a plan to embed xtion-like sensor in NEXTAGE as default, because we don't want to differ from NEXTAGE and NEXTAGE OPEN in hardware. Original NEXTAGE needs stereo camera to use with Halcon vision library.

**Comment by 130s** [comment]
Sorry for being off the boat. So do we agree to recommend users with interest in using `ueye` cameras `ueye_cam` package? No `ueye` package? If so, don't we want to ask the package maintainer to release as DEB? It's [not yet release](http://www.ros.org/debbuild/hydro.html?q=ueye) into hydro.

**Comment by k-okada** [comment]
I understand that manufacturer is not want to use xtion/kinect for their 
product. 

My intentions is  if someone is interested in hardware modification, If 
someone is interested in, we're happy to share/distribute a head mount 
attachment and create community wiki as 
http://wiki.ros.org/Robots/PR2/HardwareMods

> @k-okada Super cool package! Hope to test on stereo camera too.

As for stereo camera, Neither Isaac nor  I do not have stereo cam set 
and/or Nextage, So there is nothing we can do....., So we need help from 
you and/or people who already bought nextage.

I also understand that the manufacturer thinks gazebo (dunamics simulaotr) 
is not necessary for this kind of robots, but it is not just a dynamics 
simulator, but it can simulate whole sensor pipeline so I used pr2/baxter 
gazebo simulator to develop calibration package and that really helped.

**Comment by longjie** [comment]
Please reopen issue if it continues.

@k-okada, I definately want the mod information like xtion attachments. And I can contribute mod info and stereo camera testing. 

I'm testing the stereo cam and the depth image is not so good, I guess I need to tune more. 

And I guess NEXTAGE for manufacturing don't use the stereo cam for depth image, but for position measuring of markers, right? I wonder I should make effort to get good depth image from stereo camera. Kinect sensors are much easier...

**Comment by youtalk** [comment]
We use the stereo camera to recognize markers and also match templates with sub-millimeter (NOT sub-pixel) accuracy. It is definitely required in industries. So we cannot use depth sensor so far... 

But of course I know every researchers want to use depth sensor. We're always welcoming to mod!! It sounds very good. Please create the community and share more information.

First of all I try to tune stereo parameters and understand how to calibrate hand-eye coordinates. It's worthwhile to me :)

**Comment by youtalk** [comment]
@130s After some experiments and patches to `ueye_cam`, I think `ueye_cam` became better than `ueye` in stability and performance. I hope to use `ueye_cam` as a default ueye camera driver.

**Comment by 130s** [comment]
@youtalk and all, [I asked the author for making a DEB package](https://github.com/anqixu/ueye_cam/issues/10).

**Comment by longjie** [comment]
Hi, I'm successfully using the head stereo cameras for looking for AR markers.
BTW,  have anyone already written launch file for the hand's ueye cameras? @youtalk ?
If not, I'm going to write them hereafter.
Thank you.

**Comment by youtalk** [comment]
Sorry for my delayed progress. Recently I have less time to use NEXTAGE...
So please continue your writing, @longjie It's quite helpful.

**Comment by 130s** [comment]
FYI now `ueye_cam` is available via apt thanks to @anqixu. 
If someone can add a launch file for the cameras, we can add ueye_cam as a dependency.

**Comment by 130s** [comment]
Thanks all, now with #162 from @longjie we now have all cameras on the head and at hands working.
