### ISSUE TITLE
Add tutorial for IO

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#104]
Users want to know:
- [ ] How to read IO status
  - Explain what `readDigitalOutput` and `readDigitatIntput` methods are for.
- [ ] Which pin is for what (described in H/W manual and also in in-code doc).
- [x] How to change tools by changing DIO w/o using opensource software?

**Comment by 130s** [comment]
- How to change tools by changing DIO w/o using opensource software?

**Comment by 130s** [comment]
[Wiki page](http://wiki.ros.org/rtmros_nextage/Tutorials/Using%20digital%20IO%20%28NXO%20only%29) started.

**Comment by k-okada** [comment]
closing, if wiki page is not complete, please re-open
