### ISSUE TITLE
procedure to recover from servo on/off physical button

### ISSUE THREAD

**Issue by k-okada** [tork-a/rtmros_nextage#106]
I'd like to clarify the procedure to recover after servo on/off physical button (http://wiki.ros.org/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users?action=AttachFile&do=get&target=nxo_runstop_relayswitch.jpg)

from ipython interpreter, Does

```
$ robot.goInitial()
;; move button to servo off and on
$ robot.goActual()
$ robot.goInitial()
```

work? I think @youtalk is the only one person in this repository who is able to have access to real robot, so hope you can help.

**Comment by youtalk** [comment]
@k-okada You should use `servoOn/servoOff` methods of `hironx_client.py`. It can be more safely recovered from servo off.

https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L406
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L494

```
$ robot.goInitial()
;; move button to servo off and on
$ robot.servoOff()
$ robot.servoOn()
$ robot.goInitial()
```

You don't need to call `goActual` anymore.

**Comment by k-okada** [comment]
Thanks!

**Comment by 130s** [comment]
Related https://github.com/start-jsk/rtmros_hironx/issues/38

**Comment by 130s** [comment]
Btw is `robot.goInitial()` before-and-after the pause is required?

**Comment by youtalk** [comment]
@130s You don't need it. It's just a sample code.

**Comment by 130s** [comment]
:100:

**Comment by k-okada** [comment]
BTW, I meant "servo on/off physical button" is the red big relay button on the picture above(
http://wiki.ros.org/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users?action=AttachFile&do=get&target=nxo_runstop_relayswitch.jpg). But does `;; move button to servo off and on`  mean black switch (一旦停止／作動）?

**Comment by youtalk** [comment]
@k-okada I also meant it is the red big button. The black switch doesn't work with `hrpsys-base` so far.

**Comment by k-okada** [comment]
Ok, thanks.
