### ISSUE TITLE
Documentation or diagram for generated ROSBridges

### ISSUE THREAD

**Issue by snozawa** [tork-a/rtmros_nextage#110]
The following system diagram and documentation are quite informative:
http://wiki.ros.org/rtmros_nextage/Tutorials/Install%20NEXTAGE%20OPEN%20software%20on%20your%20machine

Now I'm finding diagrams or documentation for generated ROSBridge, such as 
`DataLoggerServiceROSBridge` and `CollisionDetectorServiceROSBridge`.

Currently, the diagram do not include these ROSBridges:
https://docs.google.com/drawings/d/12jyX6fGuVDiIJpACxixHhZ_Z8IdO1yIcJhkkrJ7B0Pk/edit

For documentation, I'm finding these explanations:
- ROSBridges is automatically generated in catkin_make based on hrpsys-base's IDLs.  
  For example, `DataLoggerServiceROSBridge` is generated from `hrpsys-base/idl/DataLoggerService.idl`. 
- Each generaed ROSBridge can take ROS services corresponding to RPC of RTM service ports each hrpsys-base RTC.  
  For example, when `/DataLoggerServiceROSBridge/clear` ROS service is called, `DataLoggerServiceROSBridge` calls `clear()` function of `log.rtc` (DataLogger RTC) through Service port.
- Documentation for ROSBridges' ROS service is API DOC of hrpsys-base or IDL files.

Is there any documentation or diagrams for generated ROSBridges like this?
If not exists, I'd like to add them.

However, users for `rtmros_nextage` package seem to use hrpsys-base RPCs through RTM python interface script instead of ROS service through generated ROSBridges.
If so, do I need to these documentation and diagrams to upstream package?

**Comment by k-okada** [comment]
> Is there any documentation or diagrams for generated ROSBridges like this? 

No, 

> If so, do I need to these documentation and diagrams to upstream package?

Yes, if the diagram is general, you can move that file to upstream package. 
@snozawa you can ask newcomer (@eisoku9618) to modify them.

**Comment by snozawa** [comment]
Thanks, I'll try it.

**Comment by k-okada** [comment]
maybe @eisoku9618 already have diagram
