### ISSUE TITLE
DIO pin array is different for newer models

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#113]
A user who received the robot in August 2014 reported that the following DIO commands don't work as claimed. We're in contact with the manufacturer (Kawada Robotics) for confirmation if the wiring has change.

[nextage_ros_bridge.nextage_client.NextageClient](http://docs.ros.org/hydro/api/nextage_ros_bridge/html/classnextage__ros__bridge_1_1nextage__client_1_1NextageClient.html)

```
def     airhand_r_drawin
def     airhand_r_keep
def     airhand_r_release
def     gripper_l_close
def     gripper_l_open
def     gripper_r_close
def     gripper_r_open
def     handtool_l_attach
def     handtool_l_eject
```

**Comment by 130s** [comment]
The change of the wiring spec is confirmed by the manufacturor. Patchwork time now.

Situation: there are 2 types of robots out there; (1) ones where DIO works with version 0.4.2 software, (2) ones DIO not working and need patch.

Requirement: Address the issues with (2) while maintaining functionality for (1) robots.

My idea is to do the following:
- Create a new script that connects to new set of DIO array, in addition to the existing [/nextage_ros_bridge/script/nextage.py](https://github.com/tork-a/rtmros_nextage/blob/4cf8cac0c3146c9badf5a128bff03b5855575352/nextage_ros_bridge/script/nextage.py). Owners of (2) can just call this new script. Let's bump the minor version to `0.5`, and call this script something like `nextage0.5.py` to indicate the version where the new spec is introduced.
- Create new set of DIO pins (this needs to be pluggable more easily than it is now).

**Comment by k-okada** [comment]
I think that is ok, for old version use, we ask them to explicitly tell script to use old spec. like

```
hiro = Hiro()
# hiro.set_dio_version("0.4.2")
hiro.....
```
