### ISSUE TITLE
runtime_error upon moveit_commander.MoveGroupCommander("left_arm") with real robot

### ISSUE THREAD

**Issue by terakoji** [tork-a/rtmros_nextage#124]
実機で以下のエラーがでる。

In [1]: import rospy

In [2]: import moveit_commander
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'

In [3]: robot = moveit_commander.RobotCommander()
[ERROR] [1415429380.219187466]: End effector 'right_eef' specified for group 'right_gripper', but that group is not known
[ERROR] [1415429380.219267602]: End effector 'left_eef' specified for group 'left_gripper', but that group is not known
[ INFO] [1415429380.219448986]: Loading robot model 'NextageOpen'...

In [4]: print robot.get_group_names()
['left_arm', 'right_arm']

In [5]: print robot.get_current_state()
joint_state: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs: 0
    frame_id: /WAIST_Link
  name: ['CHEST_JOINT0', 'HEAD_JOINT0', 'HEAD_JOINT1', 'LARM_JOINT0', 'LARM_JOINT1', 'LARM_JOINT2', 'LARM_JOINT3', 'LARM_JOINT4', 'LARM_JOINT5', 'RARM_JOINT0', 'RARM_JOINT1', 'RARM_JOINT2', 'RARM_JOINT3', 'RARM_JOINT4', 'RARM_JOINT5']
  position: [0.0, 0.0, 0.0, 0.010463248865706005, 0.0, -1.7453292519943295, -0.2652804571308041, 0.16405413199507637, -0.05584546243227205, -0.013055062804917585, -0.448709190722725, -1.1952800115820565, 0.2621639761222639, 0.06549075310413098, 0.03173556532332712]
  velocity: []
  effort: []
multi_dof_joint_state: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs: 0
    frame_id: /WAIST_Link
  joint_names: []
  transforms: []
  twist: []
  wrench: []
attached_collision_objects: []
is_diff: False
## In [6]: rarm = moveit_commander.MoveGroupCommander("right_arm")

RuntimeError                              Traceback (most recent call last)
/home/koji_terada/<ipython-input-6-8bfc6ab1dc24> in <module>()
----> 1 rarm = moveit_commander.MoveGroupCommander("right_arm")

/opt/ros/hydro/lib/python2.7/dist-packages/moveit_commander/move_group.pyc in **init**(self, name)
     49     def **init**(self, name):
     50         """ Specify the group name for which to construct this commander instance. Throws an exception if there is an initialization error. """
---> 51         self._g = _moveit_move_group_interface.MoveGroup(name, "robot_description")
     52 
     53     def get_name(self):

RuntimeError: Unable to connect to move_group action server within allotted time (2)

**Comment by terakoji** [comment]
前川さんのところからも見えていない。

こちらからrostopic pub -r 10 /hoge std_msgs/String 'data:hoge'
とかしてもrobotでtopicが見えないのが原因っぽい

**Comment by garaemon** [comment]
ROS_HOSTNAME, ROS_IPをipadressにするのが必要でしょうか?

**Comment by garaemon** [comment]
環境変数です

**Comment by terakoji** [comment]
ROS_IPはやったけどROS_HOSTNAMEはやってなかったです。
ためして見ます。

**Comment by k-okada** [comment]
```
env | grep ROS
rostopic list
```

の結果をすべて残らずカットアンドペーストしていただけると嬉しいです．

**Comment by terakoji** [comment]
ROS_IPはやったけどROS_HOSTNAMEはやってなかったです。
ためして見ます。

**Comment by terakoji** [comment]
koji_terada@ubuntu:~/catkin_ws/src/ros_nextage_painter/nextage_paint_commander/src$ env | grep ROS
ROS_ROOT=/opt/ros/hydro/share/ros
ROS_PACKAGE_PATH=/home/koji_terada/catkin_ws/src:/opt/ros/hydro/share:/opt/ros/hydro/stacks
ROS_MASTER_URI=http://ayame:11311
ROS_TEST_RESULTS_DIR=/home/koji_terada/catkin_ws/build/test_results
ROS_MAVEN_DEPLOYMENT_REPOSITORY=/home/koji_terada/catkin_ws/devel/share/maven
ROS_MAVEN_PATH=/home/koji_terada/catkin_ws/devel/share/maven:/opt/ros/hydro/share/maven
ROS_MAVEN_REPOSITORY=https://github.com/rosjava/rosjava_mvn_repo/raw/master
ROSLISP_PACKAGE_DIRECTORIES=/home/koji_terada/catkin_ws/devel/share/common-lisp
ROS_DISTRO=hydro
ROS_IP=192.168.120.225
ROS_ETC_DIR=/opt/ros/hydro/etc/ros
koji_terada@ubuntu:~/catkin_ws/src/ros_nextage_painter/nextage_paint_commander/src$ rostopic list
/attached_collision_object
/camera/left/image_raw/compressed
/camera/left/image_raw/distorted
/camera/left/image_raw/distorted/compressed
/camera/left/image_raw/distorted/compressed/parameter_descriptions
/camera/left/image_raw/distorted/compressed/parameter_updates
/camera/left/image_raw/distorted/compressedDepth
/camera/left/image_raw/distorted/compressedDepth/parameter_descriptions
/camera/left/image_raw/distorted/compressedDepth/parameter_updates
/camera/left/image_raw/distorted/theora
/camera/left/image_raw/distorted/theora/parameter_descriptions
/camera/left/image_raw/distorted/theora/parameter_updates
/camera/right/image_raw/compressed
/camera/right/image_raw/distorted
/camera/right/image_raw/distorted/compressed
/camera/right/image_raw/distorted/compressed/parameter_descriptions
/camera/right/image_raw/distorted/compressed/parameter_updates
/camera/right/image_raw/distorted/compressedDepth
/camera/right/image_raw/distorted/compressedDepth/parameter_descriptions
/camera/right/image_raw/distorted/compressedDepth/parameter_updates
/camera/right/image_raw/distorted/theora
/camera/right/image_raw/distorted/theora/parameter_descriptions
/camera/right/image_raw/distorted/theora/parameter_updates
/clicked_point
/clock
/collision_object
/fullbody_controller/command
/fullbody_controller/follow_joint_trajectory_action/cancel
/fullbody_controller/follow_joint_trajectory_action/feedback
/fullbody_controller/follow_joint_trajectory_action/goal
/fullbody_controller/follow_joint_trajectory_action/result
/fullbody_controller/follow_joint_trajectory_action/status
/fullbody_controller/joint_trajectory_action/cancel
/fullbody_controller/joint_trajectory_action/feedback
/fullbody_controller/joint_trajectory_action/goal
/fullbody_controller/joint_trajectory_action/result
/fullbody_controller/joint_trajectory_action/status
/fullbody_controller/state
/hand/nodelet_manager/bond
/hand/right/camera_info
/hand/right/image_color
/hand/right/image_color/compressed
/hand/right/image_color/compressed/parameter_descriptions
/hand/right/image_color/compressed/parameter_updates
/hand/right/image_color/compressedDepth
/hand/right/image_color/compressedDepth/parameter_descriptions
/hand/right/image_color/compressedDepth/parameter_updates
/hand/right/image_color/theora
/hand/right/image_color/theora/parameter_descriptions
/hand/right/image_color/theora/parameter_updates
/hand/right/image_mono
/hand/right/image_mono/compressed
/hand/right/image_mono/compressed/parameter_descriptions
/hand/right/image_mono/compressed/parameter_updates
/hand/right/image_mono/compressedDepth
/hand/right/image_mono/compressedDepth/parameter_descriptions
/hand/right/image_mono/compressedDepth/parameter_updates
/hand/right/image_mono/theora
/hand/right/image_mono/theora/parameter_descriptions
/hand/right/image_mono/theora/parameter_updates
/hand/right/image_proc_debayer/parameter_descriptions
/hand/right/image_proc_debayer/parameter_updates
/hand/right/image_proc_rectify_color/parameter_descriptions
/hand/right/image_proc_rectify_color/parameter_updates
/hand/right/image_proc_rectify_mono/parameter_descriptions
/hand/right/image_proc_rectify_mono/parameter_updates
/hand/right/image_raw
/hand/right/image_raw/compressed
/hand/right/image_raw/compressed/parameter_descriptions
/hand/right/image_raw/compressed/parameter_updates
/hand/right/image_raw/compressedDepth
/hand/right/image_raw/compressedDepth/parameter_descriptions
/hand/right/image_raw/compressedDepth/parameter_updates
/hand/right/image_raw/theora
/hand/right/image_raw/theora/parameter_descriptions
/hand/right/image_raw/theora/parameter_updates
/hand/right/image_rect
/hand/right/image_rect/compressed
/hand/right/image_rect/compressed/parameter_descriptions
/hand/right/image_rect/compressed/parameter_updates
/hand/right/image_rect/compressedDepth
/hand/right/image_rect/compressedDepth/parameter_descriptions
/hand/right/image_rect/compressedDepth/parameter_updates
/hand/right/image_rect/theora
/hand/right/image_rect/theora/parameter_descriptions
/hand/right/image_rect/theora/parameter_updates
/hand/right/image_rect_color
/hand/right/image_rect_color/compressed
/hand/right/image_rect_color/compressed/parameter_descriptions
/hand/right/image_rect_color/compressed/parameter_updates
/hand/right/image_rect_color/compressedDepth
/hand/right/image_rect_color/compressedDepth/parameter_descriptions
/hand/right/image_rect_color/compressedDepth/parameter_updates
/hand/right/image_rect_color/theora
/hand/right/image_rect_color/theora/parameter_descriptions
/hand/right/image_rect_color/theora/parameter_updates
/hand/ueye_cam_nodelet_master/parameter_descriptions
/hand/ueye_cam_nodelet_master/parameter_updates
/imu
/initialpose
/joint_states
/larm_controller/follow_joint_trajectory_action/cancel
/larm_controller/follow_joint_trajectory_action/feedback
/larm_controller/follow_joint_trajectory_action/goal
/larm_controller/follow_joint_trajectory_action/result
/larm_controller/follow_joint_trajectory_action/status
/motor_states
/move_base_simple/goal
/move_group/cancel
/move_group/display_contacts
/move_group/display_planned_path
/move_group/feedback
/move_group/goal
/move_group/monitored_planning_scene
/move_group/ompl/parameter_descriptions
/move_group/ompl/parameter_updates
/move_group/plan_execution/parameter_descriptions
/move_group/plan_execution/parameter_updates
/move_group/planning_scene_monitor/parameter_descriptions
/move_group/planning_scene_monitor/parameter_updates
/move_group/result
/move_group/sense_for_plan/parameter_descriptions
/move_group/sense_for_plan/parameter_updates
/move_group/status
/move_group/trajectory_execution/parameter_descriptions
/move_group/trajectory_execution/parameter_updates
/oculus/hmd_info
/oculus/orientation
/odom
/output
/pickup/cancel
/pickup/feedback
/pickup/goal
/pickup/result
/pickup/status
/place/cancel
/place/feedback
/place/goal
/place/result
/place/status
/planning_scene
/planning_scene_world
/rosout
/rosout_agg
/rviz_1415440275278024598/theora/parameter_descriptions
/rviz_1415440275278024598/theora/parameter_updates
/stereo/disparity
/stereo/left/camera_info
/stereo/left/image_color
/stereo/left/image_color/compressed
/stereo/left/image_color/compressed/parameter_descriptions
/stereo/left/image_color/compressed/parameter_updates
/stereo/left/image_color/compressedDepth
/stereo/left/image_color/compressedDepth/parameter_descriptions
/stereo/left/image_color/compressedDepth/parameter_updates
/stereo/left/image_color/theora
/stereo/left/image_color/theora/parameter_descriptions
/stereo/left/image_color/theora/parameter_updates
/stereo/left/image_mono
/stereo/left/image_mono/compressed
/stereo/left/image_mono/compressed/parameter_descriptions
/stereo/left/image_mono/compressed/parameter_updates
/stereo/left/image_mono/compressedDepth
/stereo/left/image_mono/compressedDepth/parameter_descriptions
/stereo/left/image_mono/compressedDepth/parameter_updates
/stereo/left/image_mono/theora
/stereo/left/image_mono/theora/parameter_descriptions
/stereo/left/image_mono/theora/parameter_updates
/stereo/left/image_proc_debayer/parameter_descriptions
/stereo/left/image_proc_debayer/parameter_updates
/stereo/left/image_proc_rectify_color/parameter_descriptions
/stereo/left/image_proc_rectify_color/parameter_updates
/stereo/left/image_proc_rectify_mono/parameter_descriptions
/stereo/left/image_proc_rectify_mono/parameter_updates
/stereo/left/image_raw
/stereo/left/image_raw/compressed
/stereo/left/image_raw/compressed/parameter_descriptions
/stereo/left/image_raw/compressed/parameter_updates
/stereo/left/image_raw/compressedDepth
/stereo/left/image_raw/compressedDepth/parameter_descriptions
/stereo/left/image_raw/compressedDepth/parameter_updates
/stereo/left/image_raw/theora
/stereo/left/image_raw/theora/parameter_descriptions
/stereo/left/image_raw/theora/parameter_updates
/stereo/left/image_rect
/stereo/left/image_rect/compressed
/stereo/left/image_rect/compressed/parameter_descriptions
/stereo/left/image_rect/compressed/parameter_updates
/stereo/left/image_rect/compressedDepth
/stereo/left/image_rect/compressedDepth/parameter_descriptions
/stereo/left/image_rect/compressedDepth/parameter_updates
/stereo/left/image_rect/theora
/stereo/left/image_rect/theora/parameter_descriptions
/stereo/left/image_rect/theora/parameter_updates
/stereo/left/image_rect_color
/stereo/left/image_rect_color/compressed
/stereo/left/image_rect_color/compressed/parameter_descriptions
/stereo/left/image_rect_color/compressed/parameter_updates
/stereo/left/image_rect_color/compressedDepth
/stereo/left/image_rect_color/compressedDepth/parameter_descriptions
/stereo/left/image_rect_color/compressedDepth/parameter_updates
/stereo/left/image_rect_color/theora
/stereo/left/image_rect_color/theora/parameter_descriptions
/stereo/left/image_rect_color/theora/parameter_updates
/stereo/nodelet_manager/bond
/stereo/points
/stereo/points2
/stereo/right/camera_info
/stereo/right/image_color
/stereo/right/image_color/compressed
/stereo/right/image_color/compressed/parameter_descriptions
/stereo/right/image_color/compressed/parameter_updates
/stereo/right/image_color/compressedDepth
/stereo/right/image_color/compressedDepth/parameter_descriptions
/stereo/right/image_color/compressedDepth/parameter_updates
/stereo/right/image_color/theora
/stereo/right/image_color/theora/parameter_descriptions
/stereo/right/image_color/theora/parameter_updates
/stereo/right/image_mono
/stereo/right/image_mono/compressed
/stereo/right/image_mono/compressed/parameter_descriptions
/stereo/right/image_mono/compressed/parameter_updates
/stereo/right/image_mono/compressedDepth
/stereo/right/image_mono/compressedDepth/parameter_descriptions
/stereo/right/image_mono/compressedDepth/parameter_updates
/stereo/right/image_mono/theora
/stereo/right/image_mono/theora/parameter_descriptions
/stereo/right/image_mono/theora/parameter_updates
/stereo/right/image_proc_debayer/parameter_descriptions
/stereo/right/image_proc_debayer/parameter_updates
/stereo/right/image_proc_rectify_color/parameter_descriptions
/stereo/right/image_proc_rectify_color/parameter_updates
/stereo/right/image_proc_rectify_mono/parameter_descriptions
/stereo/right/image_proc_rectify_mono/parameter_updates
/stereo/right/image_raw
/stereo/right/image_raw/compressed
/stereo/right/image_raw/compressed/parameter_descriptions
/stereo/right/image_raw/compressed/parameter_updates
/stereo/right/image_raw/compressedDepth
/stereo/right/image_raw/compressedDepth/parameter_descriptions
/stereo/right/image_raw/compressedDepth/parameter_updates
/stereo/right/image_raw/theora
/stereo/right/image_raw/theora/parameter_descriptions
/stereo/right/image_raw/theora/parameter_updates
/stereo/right/image_rect
/stereo/right/image_rect/compressed
/stereo/right/image_rect/compressed/parameter_descriptions
/stereo/right/image_rect/compressed/parameter_updates
/stereo/right/image_rect/compressedDepth
/stereo/right/image_rect/compressedDepth/parameter_descriptions
/stereo/right/image_rect/compressedDepth/parameter_updates
/stereo/right/image_rect/theora
/stereo/right/image_rect/theora/parameter_descriptions
/stereo/right/image_rect/theora/parameter_updates
/stereo/right/image_rect_color
/stereo/right/image_rect_color/compressed
/stereo/right/image_rect_color/compressed/parameter_descriptions
/stereo/right/image_rect_color/compressed/parameter_updates
/stereo/right/image_rect_color/compressedDepth
/stereo/right/image_rect_color/compressedDepth/parameter_descriptions
/stereo/right/image_rect_color/compressedDepth/parameter_updates
/stereo/right/image_rect_color/theora
/stereo/right/image_rect_color/theora/parameter_descriptions
/stereo/right/image_rect_color/theora/parameter_updates
/stereo/stereo_image_proc/parameter_descriptions
/stereo/stereo_image_proc/parameter_updates
/stereo/stereo_image_proc_debayer_left/parameter_descriptions
/stereo/stereo_image_proc_debayer_left/parameter_updates
/stereo/stereo_image_proc_debayer_right/parameter_descriptions
/stereo/stereo_image_proc_debayer_right/parameter_updates
/stereo/stereo_image_proc_rectify_color_left/parameter_descriptions
/stereo/stereo_image_proc_rectify_color_left/parameter_updates
/stereo/stereo_image_proc_rectify_color_right/parameter_descriptions
/stereo/stereo_image_proc_rectify_color_right/parameter_updates
/stereo/stereo_image_proc_rectify_mono_left/parameter_descriptions
/stereo/stereo_image_proc_rectify_mono_left/parameter_updates
/stereo/stereo_image_proc_rectify_mono_right/parameter_descriptions
/stereo/stereo_image_proc_rectify_mono_right/parameter_updates
/stereo/ueye_cam_nodelet_master/parameter_descriptions
/stereo/ueye_cam_nodelet_master/parameter_updates
/stereo/ueye_cam_nodelet_slave1/parameter_descriptions
/stereo/ueye_cam_nodelet_slave1/parameter_updates
/sugoiview
/tf
/tf_static
/trajectory_execution_event
/usb_cam/camera_info
/usb_cam/image_raw
/usb_cam/image_raw/compressed
/usb_cam/image_raw/compressed/parameter_descriptions
/usb_cam/image_raw/compressed/parameter_updates
/usb_cam/image_raw/compressedDepth
/usb_cam/image_raw/compressedDepth/parameter_descriptions
/usb_cam/image_raw/compressedDepth/parameter_updates
/usb_cam/image_raw/theora
/usb_cam/image_raw/theora/parameter_descriptions
/usb_cam/image_raw/theora/parameter_updates
/zmp
koji_terada@ubuntu:~/catkin_ws/src/ros_nextage_painter/nextage_paint_commander/src$

**Comment by garaemon** [comment]
ROSの通信をする各マシンでは，ホスト名が引けないと`rostopic list`はできるけど`rostopic echo hoge`とかはできないという状態になります．
このとき，`ROS_HOSTNAME`と`ROS_IP`にIPアドレスにすることで名前解決をせずにそこで指定したIPアドレスを利用するようになります．

**Comment by terakoji** [comment]
ログのように`ROS_IP`しか設定していないので、ちょっと不思議ですね。

**Comment by garaemon** [comment]
`ROS_HOSTNAME`を設定せずに通信出来ましたか?

http://wiki.ros.org/ROS/EnvironmentVariables

> Effecting a Node runtime: There are also several ROS environment variables that effect how a Node runs. The ROS_MASTER_URI is an important environment variable that tells a Node where the Master is. ROS_IP and ROS_HOSTNAME affect the network address of a Node and ROS_NAMESPACE lets you change its namespace. ROS_LOG_DIR lets you set the directory where log files are written. Many of these can be overridden by Remapping Arguments as well, which have precedence over environment variables.

**Comment by terakoji** [comment]
通信結局できませんでした。
以下のようにROS_IＰだけでも良いきかするのですが。

Node Environment Variables
ROS_IP/ROS_HOSTNAME
ROS_IP and ROS_HOSTNAME are optional environment variable that sets the declared network address of a ROS Node or tool. The options are mutually exclusive, if both are set ROS_HOSTNAME will take precedence. Use ROS_IP if you are specifying an IP address, and ROS_HOSTNAME if you are specifying a host name. When a ROS component reports a URI to the master or other components, this value will be used. This setting is only needed in situations where you have multiple addresses for a computer and need to force ROS to a particular one.
With the exception of 'localhost', it does not affect the actual bound address as ROS components bind to all available network interfaces. If the value is set to localhost, the ROS component will bind only to the loopback interface. This will prevent remote components from being able to talk to your local component.

**Comment by garaemon** [comment]
ROS_IPは二つの計算機どちらでも設定していますか？
もしくはDNSや/etc/hostsで名前解決できる状態になっていますか？

2014年11月9日日曜日、Koji Teradanotifications@github.comさんは書きました:

> 通信結局できませんでした。
> 以下のようにROS_IＰだけでも良いきかするのですが。
> 
> Node Environment Variables
> ROS_IP/ROS_HOSTNAME
> ROS_IP and ROS_HOSTNAME are optional environment variable that sets the
> declared network address of a ROS Node or tool. The options are mutually
> exclusive, if both are set ROS_HOSTNAME will take precedence. Use ROS_IP if
> you are specifying an IP address, and ROS_HOSTNAME if you are specifying a
> host name. When a ROS component reports a URI to the master or other
> components, this value will be used. This setting is only needed in
> situations where you have multiple addresses for a computer and need to
> force ROS to a particular one.
> With the exception of 'localhost', it does not affect the actual bound
> address as ROS components bind to all available network interfaces. If the
> value is set to localhost, the ROS component will bind only to the loopback
> interface. This will prevent remote components from being able to talk to
> your local component.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tork-a/rtmros_nextage/issues/124#issuecomment-62260886
> .

## 

from iPhone

**Comment by terakoji** [comment]
ロボット側がもしかしたら正しく設定できでなかったかもしれません。名前解決はDNSがなかったですね。

**Comment by k-okada** [comment]
```
rostopic  info /rosout # (あるいは今使おうとしているトピック）
```

としてそこで出てくるホスト名がすべてお互いのマシンで引ける，というのが全体なので，それを確認するのがいいですね．
DNSしないとちょっと難しいと思います．あと，どういう状況だったかわからないですが，各自のマシンでmoveit上げると
なんかやなことが起きそうですね．

2014-11-09 10:38 GMT+09:00 Koji Terada notifications@github.com:

**Comment by garaemon** [comment]
> あと，どういう状況だったかわからないですが，各自のマシンでmoveit上げると
> なんかやなことが起きそうですね．

たしかに、moveitのデフォルトのlaunchはほとんどnodeを固定の名前で立ち上げますね

**Comment by youtalk** [comment]
当日返信できず、すみません。現状DNSがない状況ですので、すべてのマシンに/etc/hostsでhostnameを設定した上で後日もう一度試してみます。

**Comment by k-okada** [comment]
2014-11-10 10:49 GMT+09:00 Yutaka Kondo notifications@github.com:

> すべてのマシンに/etc/hostsでhostnameを設定した上

これは結構破綻しそうなので，DHCPとDNSをもったアクセスポイントをおいておくのが良さそうですね．
でロボットとVisionPCのDNSはセットしておいて，ユーザはROS_IPを使ってもらう．うまく行けばこれを
忘れてもDNSで回避できると思うけど，みんなが同じマシン名だったりするとダメなのであくまでも保険．
という感じで．．．

**Comment by 130s** [comment]
Hard to replicate the same issue, and it looks generic ROS problem. Please feel free if we still need to continue.
