### ISSUE TITLE
Add a MoveGroup for head 

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#126]
@DaikiMaekawa has a prototype.

**Comment by 130s** [comment]
Being able to operate head via MoveIt! may seem not much valuable, but enabling developers to access joint groups via common interface (like `MoveGroup`) means (1) developers not having to learn a robot-specific interface (2) maintainers not having to maintain new I/F.

**Comment by DaikiMaekawa** [comment]
I will throw PReq after this code reorganization and bug fixes.
