### ISSUE TITLE
No travis appears

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#145]
Last time [PR was merged on Feb 3, travis must have been working since we can see a check sign](https://github.com/tork-a/rtmros_nextage/pull/140).
Today, with 2 remaining PRs travis doesn't even show its icon, nor it gets triggered.

**Comment by k-okada** [comment]
it sometimes happens, please  restart by yourself

## 

◉ Kei Okada

**Comment by 130s** [comment]
Title changed; what I meant is there's even no travis option on pull request window.

**Comment by k-okada** [comment]
![screenshot from 2015-03-09 12 52 04](https://cloud.githubusercontent.com/assets/493276/6549718/25054e0c-c65b-11e4-8bd0-d13346a31f38.png)

**Comment by 130s** [comment]
I meant this. No trait of travis.
![github_no-travis_rtmros_nextage](https://cloud.githubusercontent.com/assets/1840401/6549765/71c5b938-c65c-11e4-9f75-3b8be6297447.png)

**Comment by k-okada** [comment]
I see, but solution would be same, restart travis or add empty commit, for example just to change commit long and force update the commit

**Comment by 130s** [comment]
Hm, an empty commit added to https://github.com/tork-a/rtmros_nextage/pull/144 but still no sign of travis.

**Comment by k-okada** [comment]
I see, I create new PR #146 and change webhook ssettings but not works,
better to ask more upstream level

## 

◉ Kei Okada

**Comment by k-okada** [comment]
or start over all settings

## 

◉ Kei Okada

**Comment by 130s** [comment]
Ok I'll re-set the setting first.

**Comment by 130s** [comment]
Removed and re-added webhook then travis started working again. I suspect I might have messed up "token" on webhook page. The one I took from https://travis-ci.org/profile/info is the right one.
