### ISSUE TITLE
What is the BODY frame and how can I set it?

### ISSUE THREAD

**Issue by longjie** [tork-a/rtmros_nextage#163]
The NEXTAGE Open's root link is WAIST.
I'm getting warning that some frame has no transformation from WAIST.
- BODY
- odom
- base_footprint

odom and base_footprint is OK, they are for mobile robots. They should be somewhere on the ground.
What is the BODY frame and how can I set it?

**Comment by k-okada** [comment]
could you paste error message?
and also is it possible to reproduce this with simulator?

## 

◉ Kei Okada

**Comment by longjie** [comment]
It's not errors, just warnings. I have ignored this until moveit_planning_execution.launch produce massive waning messages to the console (as the SS I attached). I guess it is no problem to publish some tf to eliminate them. I just want to know what is the correct transform from WAIST to BODY and what BODY frame means.

And yes, this warning happens on simulator. Doing:

```
$ rtmlaunch nextage_ros_bridge nextage_ros_bridge_simulation.launch
```

and running rviz, we get same warnings "No transform from [BODY] to frame [WAIST]".
Version is 0.6.1

Thank you.

![snapx6 7](https://cloud.githubusercontent.com/assets/238460/7079629/7c4a1ff2-df61-11e4-8252-ce8cc5249b36.PNG)

**Comment by k-okada** [comment]
Although I did not get so many warnings, I have noticed that odom-> base_footprint -> BODY is orphaned . I guess it comes from [hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch](https://github.com/start-jsk/rtmros_common/blob/39245737ce3729e894aac05fa41fb41a00bc3797/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch#L234) and we have to specify `BASE_LINK` when we include hrpsys_ros_bridge.launch form nextage/hiro.

![screenshot from 2015-04-14 20 20 38](https://cloud.githubusercontent.com/assets/493276/7135689/3e15d6a0-e2e4-11e4-852f-3e4729128b55.png)
![screenshot from 2015-04-14 20 22 57](https://cloud.githubusercontent.com/assets/493276/7135692/3f6061d8-e2e4-11e4-84c2-35acaee361da.png)

**Comment by longjie** [comment]
I see. The BODY is for humanoids, to estimate the floating coordinate from gyro-sensors.
I simply added hironx_ros_bridge.launch 

```
    <arg name="BASE_LINK" value="WAIST"/>
```

and tf is now completely healthy. Thank you!

**Comment by k-okada** [comment]
great! could you commit that fix if you have time?
Thanks in advance

## 

◉ Kei Okada
