### ISSUE TITLE
Rename package to reflect the robot product name Nextage Open

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#18]
As requested from robot vendor (Kawada), `Nextage` and `Nextage Open` are different products. Since this ROS package corresponds to Open version only, they want the package name specifically distinguished.

Maybe `rtmros_nextage_open` would do?

**Comment by k-okada** [comment]
Rethink uses baxter as package name[1] although baxter and baxter research is different products, so nextage seems ok for users.

[1] https://github.com/RethinkRobotics

**Comment by emijah** [comment]
However, ordinary Nextage users may try to install this and overwhelm the support page with complaints.

**Comment by k-okada** [comment]
looking from different point of view, that's good for opensource community to let closed nextage users know about opensource nextage.

**Comment by emijah** [comment]
Ah, nice point. However, if you use the other name you can also spread awareness of the "Open" version. ;)

**Comment by 130s** [comment]
Because the possible change to the package name would have more impact
later on users side, I propose this to be resolved soon.

If the robot vendor has a reason for a new name, I think community will
respect it. That doesn't, however, guarantee that someone will volunteer to
work on (incl. changing names and doing all the regression tests).

**Comment by 130s** [comment]
I said:

> Because the possible change to the package name would have more impact later on users side, I propose this to be resolved soon.

I guess now it's getting more painful to change the package names since the user base is becoming larger (good for us!). 

If this is critical I would like to expect for contribution from community. Until then I close this.
