### ISSUE TITLE
nextage.py always requires moveit

### ISSUE THREAD

**Issue by k-okada** [tork-a/rtmros_nextage#184]
nextage.py always request moveit / ros environment, but I'd like to use them as a command line interface with rtm only environment like http://wiki.ros.org/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_RTM

question from Yang-san @ waseda

**Comment by k-okada** [comment]
fixed in https://github.com/start-jsk/rtmros_hironx/pull/380

**Comment by 130s** [comment]
Fixed via https://github.com/start-jsk/rtmros_hironx/pull/380
