### ISSUE TITLE
About real time joystick control

### ISSUE THREAD

**Issue by kuochiyoug** [tork-a/rtmros_nextage#188]
Hi! I am now doing work on joystick controlling on Nextage Open Robot.
I had tried use moveit_commander in python code but it not works very well.
Seems moveit only provide target pose solution but no trajectory speed control.
I can only do is keep sending following command in every loop:

``` python
while not rospy.is_shutdown():  
  [rarm_current_pose,larm_current_pose] = self.GetAllCurrentPose()
  target_pose_right.position.x = rarm_current_pose.position.x + self.mouse.x
  target_pose_right.position.y = rarm_current_pose.position.y + self.mouse.y
  target_pose_right.position.z = rarm_current_pose.position.z + self.mouse.z
  target_pose_right.orientation.x = rarm_current_pose.orientation.x
  target_pose_right.orientation.y = rarm_current_pose.orientation.y
  target_pose_right.orientation.z = rarm_current_pose.orientation.z
  target_pose_right.orientation.w = rarm_current_pose.orientation.w
  rarm.set_pose_target(target_pose_right)
  rarm.go(wait = True)
```

The movement that build by this code is not going very well.
All movement has delay in every executions.
I actually want a smooth movement so that I can do my following research.
Can anyone give me a good advice?

Thanks you very much!

**Comment by k-okada** [comment]
if you'd like to use realtime-control, you'd better to call via ros/hrpsys interface, not move interface.

http://wiki.ros.org/rtmros_nextage/Tutorials/Programming may help.

**Comment by kuochiyoug** [comment]
Oh!
Thanks you very much!
It works with it.!

**Comment by 130s** [comment]
I'm closing @kuochiyoug since I assume your original issue is resolved. Please feel free to reopen (or even better to open as new ticket) if you come up with specific questions.
