### ISSUE TITLE
Add full unittest suite

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#2]

**Comment by 130s** [comment]
As noted in #7, we should consider integrating `unittest`s with other rtmros-based components as much as possible. Test cases have been accumulated [here](https://code.google.com/p/rtm-ros-robotics/source/browse/#svn%2Ftrunk%2Frtmros_hironx%2Fhironx_ros_bridge%2Ftest).

**Comment by 130s** [comment]
[Started](https://github.com/tork-a/rtmros_nextage/tree/b53fdb3adffe3a4d3f90a7ba9435e786b05f8db7/nextage_ros_bridge/test)

**Comment by emijah** [comment]
Nice

**Comment by 130s** [comment]
test files need to be installed. I'll do

**Comment by 130s** [comment]
Done in [hironx_ros_bridge package](https://github.com/start-jsk/rtmros_hironx/tree/groovy-devel/hironx_ros_bridge/test).
