### ISSUE TITLE
RTCmanager connection issue

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#25]
(Update) Originally titled as `[hrpsys.py]  wait for RTCmanager :  None`, but over time related issues are succeeding so I've renamed with more general title.

---

On `Raring` using the commit https://github.com/tork-a/rtmros_nextage/commit/49d636ae9b9e7ff436bafd67b615dd0b12764918 for rtmros_nextage and [this commit](http://code.google.com/p/rtm-ros-robotics/source/detail?r=6773) for `hironx`, I get:

```
$ rtls 192.168.128.10:15005/
ModelLoader  nextage.host_cxt/  RobotHardware0.rtc
$ ipython -i `rospack find nextage_ros_bridge`/script/nextage.py RobotHardware0 /opt/jsk/etc/HIRONX/model/main.wrl -- -ORBInitRef NameService=corbaloc:iiop:192.168.128.10:15005/NameService
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
configuration ORB with  130s-t440s : 15005
[hrpsys.py]  waiting ModelLoader
[hrpsys.py]  start hrpsys
[hrpsys.py]  finding RTCManager and RobotHardware
Manager not found
[hrpsys.py]  wait for RTCmanager :  None
Manager not found
[hrpsys.py]  wait for RTCmanager :  None
Manager not found
:
```

With slightly differentl command arguments ([as suggested here](https://github.com/start-jsk/hironx-package/issues/64#issuecomment-32251541)), the result becoomes different:

```
$ ipython -i `rospack find nextage_ros_bridge`/script/nextage.py --  --host 192.168.128.10 --robot RobotHardware0 --port 15005 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
configuration ORB with  130s-t440s : 15005
---------------------------------------------------------------------------
TRANSIENT                                 Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    176             else:
    177                 filename = fname
--> 178             __builtin__.execfile(filename, *where)

/home/n130s/data/Dropbox/ROS/hydro_raring/catkinws/src/tork-a/rtmros_nextage/nextage_ros_bridge/script/nextage.py in <module>()
     66         args.robot = unknown[0]
     67         args.modelfile = unknown[1]
---> 68     nxc = nextage_client.NextageClient()
     69     nxc.init(robotname=args.robot, url=args.modelfile)
     70 

/home/n130s/data/Dropbox/ROS/hydro_raring/catkinws/src/tork-a/rtmros_nextage/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.pyc in __init__(self)
     64         super class as the tradition there.
     65         '''
---> 66         super(NextageClient, self).__init__()
     67         self._hand = NextageHand(self)
     68 

/home/n130s/link/ROS/hydro_raring/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in __init__(self, cname)
    721 
    722     def __init__(self, cname="[hrpsys.py] "):
--> 723         initCORBA()
    724         self.configurator_name = cname
    725 

/home/n130s/link/ROS/hydro_raring/catkinws/devel/lib/python2.7/dist-packages/hrpsys/rtm.pyc in initCORBA()
    270 
    271         nameserver = orb.resolve_initial_references("NameService");
--> 272         rootnc = nameserver._narrow(CosNaming.NamingContext)
    273         return None
    274 

/usr/lib/python2.7/dist-packages/omniORB/CORBA.pyc in _narrow(self, dest)
    796         except KeyError:
    797             pass
--> 798         return _omnipy.narrow(self, repoId, 1)
    799 
    800     def _unchecked_narrow(self, dest):

TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
```

**Comment by 130s** [comment]
Inside the robot on QNX,

```
$ more /opt/jsk/var/log/rtcd.log                
Logger::Logger: streambuf address = 0x805fc70
hrpExecutionContext is registered
pdgains.file_name: /opt/jsk/etc/HIRONX/hrprtc/PDgains.sav
dof = 15
open_iob - NEXTAGE OPEN  I/F v1 instance at 0x80b8e08
-- NEXTAGE::OpenV10::open_iob - shmif instance at 0x80b7ee8

the number of gyros = 0
the number of accelerometers = 0
the number of force sensors = 0
open_iob - inxifv1 isn't NULL, ignored
period = 5[ms], priority = 49
```

**Comment by emijah** [comment]
hmmm, Can you please add the output from when you do,

```
prompt> export ORBtraceLevel=40
```

before ipython

**Comment by k-okada** [comment]
--ORBInitRef.. option is deprecated, use --host and --port

**Comment by k-okada** [comment]
configuration ORB with  130s-t440s : 15005
 should be
configuration ORB with 192.168.128.10: 15005
???
please force fix rtm.py with
        nshost = '192.168.128.10'
        print "configuration ORB with ", nshost, ":", nsport
and see what's happens

**Comment by k-okada** [comment]
I'm not sure but we have to change nextage.py as follows, to use --host command option

```
from nextage_ros_bridge import nextage_client

from hrpsys import rtm
#import rtm                                                                                                           
import argparse
```

**Comment by emijah** [comment]
Ah, this makes more sense

**Comment by 130s** [comment]
(sending via email doesn't reflect formatting blah)

With this suggested change:

```
from nextage_ros_bridge import nextage_client

from hrpsys import rtm
#import rtm                                                                                                           
import argparse
```

Error msg changed:

```
$ rtls 192.168.128.10:15005/ModelLoader
nextage.host_cxt/  RobotHardware0.rtc
$ ipython -i `rospack find nextage_ros_bridge`/script/nextage.py --  --host 192.168.128.10 --robot RobotHardware0 --port 15005 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
configuration ORB with  192.168.128.10 : 15005
[hrpsys.py]  waiting ModelLoader
[hrpsys.py]  start hrpsys
[hrpsys.py]  finding RTCManager and RobotHardware
---------------------------------------------------------------------------
herror                                    Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    176             else:
    177                 filename = fname
--> 178             __builtin__.execfile(filename, *where)

/home/n130s/catkinws/src/tork-a/rtmros_nextage/nextage_ros_bridge/script/nextage.py in <module>()
     67         args.modelfile = unknown[1]
     68     nxc = nextage_client.NextageClient()
---> 69     nxc.init(robotname=args.robot, url=args.modelfile)
     70 
     71 # for simulated robot

/home/n130s/catkinws/src/tork-a/rtmros_nextage/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.pyc in init(self, robotname, url)
     77         @type url: str
     78         '''
---> 79         HIRONX.init(self, robotname=robotname, url=url)
     80 
     81     def turn_handlight_r(self, is_on=True):

/home/n130s/catkinws/src/rtm-ros-robotics/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.pyc in init(self, robotname, url)
     95         @type url: str
     96         '''
---> 97         HrpsysConfigurator.init(self, robotname=robotname, url=url)
     98         self.setSelfGroups()
     99 

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in init(self, robotname, url)
    703 
    704         print self.configurator_name, "finding RTCManager and RobotHardware"
--> 705         self.waitForRTCManagerAndRoboHardware(robotname)
    706         self.sensors = self.getSensors(url)
    707 

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in waitForRTCManagerAndRoboHardware(self, robotname, managerhost)
    510 
    511     def waitForRTCManagerAndRoboHardware(self, robotname="Robot", managerhost=nshost):
--> 512         self.waitForRTCManager(managerhost)
    513         self.waitForRobotHardware(robotname)
    514         self.checkSimulationMode()

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in waitForRTCManager(self, managerhost)
    473             if managerhost == "localhost":
    474                 managerhost = socket.gethostname()
--> 475             self.ms = rtm.findRTCmanager(managerhost)
    476             print self.configurator_name, "wait for RTCmanager : ", managerhost
    477 

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/rtm.pyc in findRTCmanager(hostname, rnc)
    335         mgr = None
    336         hostnames = [hostname, hostname.split(".")[0],
--> 337                      socket.gethostbyaddr(hostname)[0],
    338                      socket.gethostbyaddr(hostname)[0].split(".")[0]]
    339         for h in hostnames:

herror: [Errno 1] Unknown host
```

At `[hrpsys.py]  finding RTCManager and RobotHardware` it halts for a few second.

**Comment by emijah** [comment]
Can you see what managerhost is at hrpsys_config.py:475.

**Comment by 130s** [comment]
[hrpsys.py]  130s-DEBUG) wait for RTCmanager :  None

**Comment by k-okada** [comment]
I suspect this fixes did not needed -> https://github.com/start-jsk/hironx-package/issues/64#issuecomment-32150815

**Comment by 130s** [comment]
Hardcoding `rtm.py` like this still causes the same/similar error.

```
rootnc = None
#nshost = None
nshost = '192.168.128.10'  ##DEBUG 130s
nsport = None
```

```
$ ipython -i `rospack find nextage_ros_bridge`/script/nextage.py --  --host 192.168.128.10 --robot RobotHardware0 --port 15005 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
configuration ORB with  192.168.128.10 : 15005
[hrpsys.py]  waiting ModelLoader
[hrpsys.py]  start hrpsys
[hrpsys.py]  finding RTCManager and RobotHardware
[hrpsys.py]  130s-DEBUG) wait for RTCmanager :  192.168.128.10
---------------------------------------------------------------------------
herror                                    Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    176             else:
    177                 filename = fname
--> 178             __builtin__.execfile(filename, *where)

/home/n130s/catkinws/src/tork-a/rtmros_nextage/nextage_ros_bridge/script/nextage.py in <module>()
     66         args.modelfile = unknown[1]
     67     nxc = nextage_client.NextageClient()
---> 68     nxc.init(robotname=args.robot, url=args.modelfile)
     69 
     70 # for simulated robot

/home/n130s/catkinws/src/tork-a/rtmros_nextage/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.pyc in init(self, robotname, url)
     77         @type url: str
     78         '''
---> 79         HIRONX.init(self, robotname=robotname, url=url)
     80 
     81     def turn_handlight_r(self, is_on=True):

/home/n130s/catkinws/src/rtm-ros-robotics/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.pyc in init(self, robotname, url)
     95         @type url: str
     96         '''
---> 97         HrpsysConfigurator.init(self, robotname=robotname, url=url)
     98         self.setSelfGroups()
     99 

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in init(self, robotname, url)
    704 
    705         print self.configurator_name, "finding RTCManager and RobotHardware"
--> 706         self.waitForRTCManagerAndRoboHardware(robotname)
    707         self.sensors = self.getSensors(url)
    708 

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in waitForRTCManagerAndRoboHardware(self, robotname, managerhost)
    511 
    512     def waitForRTCManagerAndRoboHardware(self, robotname="Robot", managerhost=nshost):
--> 513         self.waitForRTCManager(managerhost)
    514         self.waitForRobotHardware(robotname)
    515         self.checkSimulationMode()

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.pyc in waitForRTCManager(self, managerhost)
    474                 managerhost = socket.gethostname()
    475             print self.configurator_name, "130s-DEBUG) wait for RTCmanager : ", managerhost
--> 476             self.ms = rtm.findRTCmanager(managerhost)
    477             print self.configurator_name, "wait for RTCmanager : ", managerhost
    478 

/home/n130s/catkinws/devel/lib/python2.7/dist-packages/hrpsys/rtm.py in findRTCmanager(hostname, rnc)
    336         mgr = None
    337         hostnames = [hostname, hostname.split(".")[0],
--> 338                      socket.gethostbyaddr(hostname)[0],
    339                      socket.gethostbyaddr(hostname)[0].split(".")[0]]
    340         for h in hostnames:

herror: [Errno 1] Unknown host
```

**Comment by k-okada** [comment]
what is hostname variable in 338 of rtm.py?

**Comment by 130s** [comment]
@k-okada 

> I suspect this fixes does not needed -> start-jsk/hironx-package#64 (comment)

I'm not using that change (that is only tentatively applied on Ubuntu with nxc100).

**Comment by 130s** [comment]
rtm.py

```
        print('130s-DEBUG) hostname=', hostname)
        hostnames = [hostname, hostname.split(".")[0],
                     socket.gethostbyaddr(hostname)[0],
                     socket.gethostbyaddr(hostname)[0].split(".")[0]]
```

Result:

> ('130s-DEBUG) hostname=', '192.168.128.10')

**Comment by k-okada** [comment]
so, please check 

```
$ pytnon
> import socket
> hostname='192.168.128.10'
> hostname.split(".")[0]
> socket.gethostbyaddr(hostname)
```

**Comment by k-okada** [comment]
I see, this code assumes you use hostname, not ip address for --host option. try with nx010 or something. or remove, hostname.split(".")[0],

**Comment by emijah** [comment]
This would use "192" as the hostname.

**Comment by 130s** [comment]
Now asking a robot "owner" if he can set `hostname` on this robot...

**Comment by 130s** [comment]
(Btw this error `herror: [Errno 1] Unknown host` occurs both on `Raring` and on `Precise`)

**Comment by k-okada** [comment]
add ticket at here -> http://code.google.com/p/hrpsys-base/issues/detail?id=173

quick hack might be....

```
    # fqdn                                                                                                        
    mgr = None
    hostnames = [hostname, hostname.split(".")[0]]
    try:
            hostnames.append(socket.gethostbyaddr(hostname)[0])
            hostnames.append(socket.gethostbyaddr(hostname)[0].split(".")[0])
    except:
            print 'could not find gethostbyaddr(', hostname,')'
            pass
```

**Comment by 130s** [comment]
Worked with `hostname`:

```
 $ ipython -i `rospack find nextage_ros_bridge`/script/nextage.py --  --host nextage --robot RobotHardware0 --port 15005 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl
```

**Comment by 130s** [comment]
Ok we can leave this issue to http://code.google.com/p/hrpsys-base/issues/detail?id=173 and close. Thank you so much!!!

**Comment by 130s** [comment]
Hope [this issue](http://code.google.com/p/hrpsys-base/issues/detail?id=173) in `hrpsys-base` will soon be addressed. I just needed [this [patch](https://github.com/start-jsk/rtmros_hironx/pull/3) in another robot client.

**Comment by k-okada** [comment]
本件，以下にテストプログラムをつくりましたが，これは何が悪かったんでしたでしたっけ？
https://github.com/start-jsk/hrpsys/pull/1

テストプログラムの結果は以下のようになるんですが（実際はrostestで結果が表示されないのと，
以下はデバッグコードがふんだんに取り込まれていますが），hostname='unknown'の時（名前が引けない時）

  File
"/home/k-okada/catkin_ws/ws_hrpsys/devel/lib/python2.7/dist-packages/hrpsys/rtm.py",
line 337, in findRTCmanager
    socket.gethostbyaddr(hostname)[0],
socket.gaierror: [Errno -2] Name or service not known

という表示がでるんですが，これがわかりづらい，という話でしたでしょうか？

以下の部分からすると，hostnameがIPのときにhostname.split(".")[0]が192を返しますが，
それの前のところで，hostnames = [hostname] になっているからOKに見えますが，ちがいましたでしょうか？

rtm.py

```
    print('130s-DEBUG) hostname=', hostname)
    hostnames = [hostname, hostname.split(".")[0],
                 socket.gethostbyaddr(hostname)[0],
                 socket.gethostbyaddr(hostname)[0].split(".")[0]]
```

Result:

('130s-DEBUG) hostname=', '192.168.128.10'

$ ./test-hostname.py
configuration ORB with  kokada-t430s : 2809
['kokada-t430s', 'kokada-t430s', 'kokada-t430s', 'kokada-t430s']
<rtm.RTCmanager instance at 0x3b3e488> <rtm.RTcomponent instance at
0x3b3e680>
configuration ORB with  localhost : 2809
['localhost', 'localhost', 'localhost', 'localhost']
<rtm.RTCmanager instance at 0x3b3e8c0> <rtm.RTcomponent instance at
0x3b3e7e8>
configuration ORB with  127.0.0.1 : 2809
['127.0.0.1', '127', 'localhost', 'localhost']
<rtm.RTCmanager instance at 0x3b3e950> <rtm.RTcomponent instance at
0x3b3e830>
configuration ORB with  kokada-t430s : 2809
['kokada-t430s', 'kokada-t430s', 'kokada-t430s', 'kokada-t430s']
<rtm.RTCmanager instance at 0x3b3e3f8> <rtm.RTcomponent instance at
0x3b3e908>
configuration ORB with  unknown : 2809
Traceback (most recent call last):
  File "./test-hostname.py", line 22, in <module>
    test_initCORBA('unknown')
  File "./test-hostname.py", line 14, in test_initCORBA
    ms = rtm.findRTCmanager()
  File
"/home/k-okada/catkin_ws/ws_hrpsys/devel/lib/python2.7/dist-packages/hrpsys/rtm.py",
line 337, in findRTCmanager
    socket.gethostbyaddr(hostname)[0],
socket.gaierror: [Errno -2] Name or service not known

**Comment by k-okada** [comment]
それとも，セットしたIPが間違えているかネットワークがとどかなくて，
herror: [Errno 1] Unknown host
と出ているけど，気が付きにくい，ということでしょうか？

2014-02-18 2:32 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:

> 本件，以下にテストプログラムをつくりましたが，これは何が悪かったんでしたでしたっけ？
> https://github.com/start-jsk/hrpsys/pull/1
> 
> テストプログラムの結果は以下のようになるんですが（実際はrostestで結果が表示されないのと，
> 以下はデバッグコードがふんだんに取り込まれていますが），hostname='unknown'の時（名前が引けない時）
> 
>   File
> "/home/k-okada/catkin_ws/ws_hrpsys/devel/lib/python2.7/dist-packages/hrpsys/rtm.py",
> line 337, in findRTCmanager
>     socket.gethostbyaddr(hostname)[0],
> socket.gaierror: [Errno -2] Name or service not known
> 
> という表示がでるんですが，これがわかりづらい，という話でしたでしょうか？
> 
> 以下の部分からすると，hostnameがIPのときにhostname.split(".")[0]が192を返しますが，
> それの前のところで，hostnames = [hostname] になっているからOKに見えますが，ちがいましたでしょうか？
> 
> rtm.py
> 
> ```
>     print('130s-DEBUG) hostname=', hostname)
>     hostnames = [hostname, hostname.split(".")[0],
>                  socket.gethostbyaddr(hostname)[0],
>                  socket.gethostbyaddr(hostname)[0].split(".")[0]]
> ```
> 
> Result:
> 
> ('130s-DEBUG) hostname=', '192.168.128.10'
> 
> $ ./test-hostname.py
> configuration ORB with  kokada-t430s : 2809
> ['kokada-t430s', 'kokada-t430s', 'kokada-t430s', 'kokada-t430s']
> <rtm.RTCmanager instance at 0x3b3e488> <rtm.RTcomponent instance at
> 0x3b3e680>
> configuration ORB with  localhost : 2809
> ['localhost', 'localhost', 'localhost', 'localhost']
> <rtm.RTCmanager instance at 0x3b3e8c0> <rtm.RTcomponent instance at
> 0x3b3e7e8>
> configuration ORB with  127.0.0.1 : 2809
> ['127.0.0.1', '127', 'localhost', 'localhost']
> <rtm.RTCmanager instance at 0x3b3e950> <rtm.RTcomponent instance at
> 0x3b3e830>
> configuration ORB with  kokada-t430s : 2809
> ['kokada-t430s', 'kokada-t430s', 'kokada-t430s', 'kokada-t430s']
> <rtm.RTCmanager instance at 0x3b3e3f8> <rtm.RTcomponent instance at
> 0x3b3e908>
> configuration ORB with  unknown : 2809
> Traceback (most recent call last):
>   File "./test-hostname.py", line 22, in <module>
>     test_initCORBA('unknown')
>   File "./test-hostname.py", line 14, in test_initCORBA
>     ms = rtm.findRTCmanager()
>   File
> "/home/k-okada/catkin_ws/ws_hrpsys/devel/lib/python2.7/dist-packages/hrpsys/rtm.py",
> line 337, in findRTCmanager
>     socket.gethostbyaddr(hostname)[0],
> socket.gaierror: [Errno -2] Name or service not known
> 
> On Fri, Feb 14, 2014 at 2:23 PM, Isaac Isao Saito <

**Comment by 130s** [comment]
The issue was when `HrpsysConfigurator` client (eg. Hironx, NextageClient) tries to connect to a real robot, `hostname` of the robot got overwritten with that of the machine where the client program runs on ([this ticket](https://github.com/tork-a/rtmros_nextage/issues/25) does not clearly state what the exact problem was..).

**Comment by emijah** [comment]
It seems that the module that gets called, is not the one that has the global variables set. So initCORBA is called with nshost and nsport set to "None".
If --ORBInitRef is not set, the hostname defaults to the environment the script is running on.

**Comment by k-okada** [comment]
I see, I create test code to check this problem. https://github.com/start-jsk/rtmros_common/pull/323, https://github.com/k-okada/rtmros_common/blob/master/hrpsys_tools/test/test-hrpsys-config.test,https://github.com/k-okada/rtmros_common/blob/master/hrpsys_tools/test/test-hrpsys-config.py
