### ISSUE TITLE
cartesian minimum increments is still 0.005

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#27]
With `315.1.5-0precise-20131231-0434-+0000` that I think includes [patches here](https://code.google.com/p/hrpsys-base/issues/detail?id=168), increments `0.001` (discussed [here](https://code.google.com/p/rtm-ros-robotics/issues/detail?id=267) doesn't seem to be achievable yet. 

With this snippet of code, arm moves only occasionally:

```
for i in range(500):
            pos[0] += 0.0001
            time.sleep(0.11)
            print('#', i, ' pos=', pos, ' rpy=', rpy)
            nxc.setTargetPose('rarm', pos, rpy, tm)
```

**Comment by 130s** [comment]
Maybe `hrpsys` on robot's side might have not been updated yet?

**Comment by k-okada** [comment]
You have to check hrpsys version on robot side

**Comment by 130s** [comment]
Sounds like binary in robot is old. Invalid.

(I'm using binary I copied from previous robot where it turned out someone recently re-built without me knowing it...)
