### ISSUE TITLE
robot.setTargetPose failed IK error

### ISSUE THREAD

**Issue by shzargar** [tork-a/rtmros_nextage#270]
Hello, 

On a real robot (nextage open), I used these commands as per http://wiki.ros.org/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_RTM, but I got the error.
```
In [15]: robot.goInitial()
[hrpsys.py] , JntAnglesOfGr=torso, INITPOSE[i]=[0], tm=7, wait=True
[hrpsys.py] , JntAnglesOfGr=head, INITPOSE[i]=[0, 0], tm=7, wait=True
[hrpsys.py] , JntAnglesOfGr=rarm, INITPOSE[i]=[-0.6, 0, -100, 15.2, 9.4, 3.2], tm=7, wait=True
[hrpsys.py] , JntAnglesOfGr=larm, INITPOSE[i]=[0.6, 0, -100, -15.2, 9.4, -3.2], tm=7, wait=True
Out[15]: True

In [16]: pos = robot.getCurrentPosition('RARM_JOINT3')

In [17]: rpy = robot.getReferenceRPY('RARM_JOINT3')

In [18]: tm = 3

In [19]: pos[2] = 0.5

In [20]: robot.setTargetPose('rarm', pos, rpy, tm)
('rarm', None, [0.00421516966360732, -0.1644593228255238, 0.5], (3.1402635341586285, -1.4049751443825462, 3.087243183706025), 3)
setTargetPose failed. Maybe SequencePlayer failed to solve IK.
Currently, returning IK result error
(like the one in https://github.com/start-jsk/rtmros_hironx/issues/103) is not implemented. Patch is welcomed.
Out[20]: False
```

**Comment by 130s** [comment]
Thanks for pointing that out. Although the page states "Then randomly manipulate position", it doesn't mean that we can leave non-working code sample in the tutorial. The piece of the code you referred to was written years old and I don't know if there has been changes that made it not to work. I [updated the tutorial](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_RTM?action=diff&rev2=19&rev1=18) with the values that work on my simulation environment.
