### ISSUE TITLE
Implement more permissible tolerance

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#29]
AFA we've figured out today with @emijah, the path of the arm going to backside would be very aggressively passing near the base, and depending on the attached gripper's condition it can easily hit the base.

**Comment by emijah** [comment]
It would be nice if we can lower the robot, so that the robot looks to be closer to the base than it actually is.

**Comment by 130s** [comment]
Looks like padding is now integrated into MoveIt! on its upstream repository. We can test via source or wait until its new deb will be available.

**Comment by 130s** [comment]
https://github.com/ros-planning/moveit_ros/issues/402 Link to the enhancement in MoveIt!

**Comment by 130s** [comment]
Escalated [to upstream](https://github.com/start-jsk/rtmros_hironx/issues/91).
