### ISSUE TITLE
Incorrect wiki description - Run rtm_ros_bridge (Nextage Open)

### ISSUE THREAD

**Issue by y-yosuke** [tork-a/rtmros_nextage#294]
Incorrect
```
$ roslaunch nextage_ros_bridge nextage_ros_bridge.launch nameserver:=%HOSTNAME%  (NEXTAGE OPEN)
```

Correct - "_real" is needed.
```
$ roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch nameserver:=%HOSTNAME%  (NEXTAGE OPEN)
```

**Comment by k-okada** [comment]
thanks, if you mean "manual" to
http://wiki.ros.org/rtmros_nextage/Tutorials/Operating%20Hiro,%20NEXTAGE%20OPEN,
feel free to login and fix this


--
◉ Kei Okada


2017-02-14 16:03 GMT+09:00 Yosuke Yamamoto <notifications@github.com>:

**Comment by y-yosuke** [comment]
Thanks a lot, I forgot to paste the link.
Yes, I mean "manual" is http://wiki.ros.org/rtmros_nextage/Tutorials/Operating%20Hiro,%20NEXTAGE%20OPEN#Run_rtm_ros_bridge .

I applied for permission to edit wiki, so I will edit it after acceptance.

**Comment by y-yosuke** [comment]
I fixed wiki and close this issue.
