### ISSUE TITLE
How integrate velocity in moveit_commander

### ISSUE THREAD

**Issue by shzargar** [tork-a/rtmros_nextage#296]
When using compute_cartesian_path or set_pose_target, how we can control the velocity?

**Comment by 130s** [comment]
This seems not a NEXTAGE-specific question. As I [updated the NEXTAGE tutorial](http://wiki.ros.org/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_MOVEIT#Introduction), MoveIt! has its own, thoroughly explained tutorial set. You're advised to work on that tutorial as well should you plan to write any intermediate/advanced tasks. 

And questions that are not specific to NEXTAGE should receive far better response on ROS' designated forum called Answers.

- [MoveIt! tutorial](http://docs.ros.org/api/moveit_tutorials/html)
- [ROS Answers](http://answers.ros.org/)
  - For your specific question, you might also want to refer to [this thread on Answers](http://answers.ros.org/question/251282/how-to-change-velocity-acceleration-in-motionplanrequest-topic/).
