### ISSUE TITLE
How to check QNX version?

### ISSUE THREAD

**Issue by shzargar** [tork-a/rtmros_nextage#303]
Hello,

As it is mentioned in [http://wiki.ros.org/rtmros_nextage/Tutorials/Adding%20feedback%20control](url) for Impedance Control,  QNX 6.5.0 is required. How to check if ours has the same version?

Thanks

**Comment by 130s** [comment]
I'd say you'll most likely not need to check the version. Unlike Ubuntu or other opensource OSes, `QNX` won't upgrade over the internet AFAIK so it should stay the same version 6.5.0 unless robot owners explicitly upgraded. 

Currently there's no plan for NEXTAGE Open software to be upgraded to higher version of QNX.

Please feel free for the further inquiries.
