### ISSUE TITLE
Model is different from actual robot?

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#31]
We noticed that at least around EEF. More detail to come.
@emijah might be posting high-resolution pictures now.

**Comment by emijah** [comment]
Pictures have been shared.

**Comment by 130s** [comment]
Example. You see the white beam is shorter in RViz, which can in the worst case lead to unexpectable collision.
![dsc03633](https://cloud.githubusercontent.com/assets/1840401/4423984/1b87eb42-459a-11e4-89b3-905ba3f577f4.jpg)
![dsc03630](https://cloud.githubusercontent.com/assets/1840401/4423985/1b9c2f6c-459a-11e4-9c76-3ae127f6617c.jpg)

**Comment by emijah** [comment]
It may be better to just adjust the model. Going through Kawada will be quite a hassle.
That way you can "develop" a TORK version of the model that you can adjust according to your free will.

**Comment by k-okada** [comment]
@emijah is the only one who owns nextage robot, so please update model 
files, thanks!

## 

◉ Kei Okada

**Comment by emijah** [comment]
gaaaaa

**Comment by 130s** [comment]
I think we can continue this in #244.

**Comment by k-okada** [comment]
Now i understand why you mentioned the "black box" at
https://github.com/tork-a/rtmros_nextage/issues/244#issuecomment-216446999
this issue address difference in geometry model where as #244 is discussing
about the kinematics of the model.

## 

◉ Kei Okada

**Comment by 130s** [comment]
> this issue address difference in geometry model where as #244 is discussing about the kinematics of the model.

Isn't the root cause of #244 the difference of model geometry between Hiro and NXO?

**Comment by k-okada** [comment]
sorry geometry means shape (of each links), which is independent from
kinematics of the robots

## 

◉ Kei Okada
