### ISSUE TITLE
(Tutorial) add your own hand module

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#33]
I'm assigning myself but I'll keep my work in full-opensource manner. Your review, correction is appreciated.

**Comment by 130s** [comment]
Started on ROS wiki that everyone can edit.
http://wiki.ros.org/rtmros_nextage/Tutorials/To%20write%20a%20hand%20module%20for%20Nextage%20Open

fyi @emijah

**Comment by k-okada** [comment]
I have updatead wiki, this examples SuctionHand.wrl but it is not public right now, so no one can test this tutorial nor  we can not put images to show how it works. @emijah, can you put SuctionHand.wrl to the repository? or we have to ask somebody for example gripper model.

**Comment by emijah** [comment]
I'm on it. I'll need to check permission too.

**Comment by emijah** [comment]
The title seems a bit odd.
http://wiki.ros.org/rtmros_nextage/Tutorials/To write a hand module for
Nextage Open

How about "Writing Hand Modules for Nextage Open"?

2014-01-28 Kei Okada notifications@github.com

**Comment by k-okada** [comment]
I see
If uses want to change grippers on the real robot, they will look for documtns named
-  Changing Nextage Grippers or Changing Grippers on Nextage Robot

Then, they will notice that they have to change grippers on software system, so how about
- Changing Nextage Grippers in Robot Model ?
- Changing Nextage Grippers in Simulated Robot?

**Comment by emijah** [comment]
Yes, that suggestion is best.

**Comment by k-okada** [comment]
ok , I have changed the page title http://wiki.ros.org/rtmros_nextage/Tutorials/Changing%20Nextage%20Grippers%20in%20Robot%20Model

Hajime-san, can you get permission for SuctionHand.wrl? we need this one to finish the documents

**Comment by 130s** [comment]
python module writing part done
http://wiki.ros.org/rtmros_nextage/Tutorials/Changing%20Nextage%20Grippers%20in%20Robot%20Model#Create_Software_In_Python

**Comment by 130s** [comment]
@k-okada could you upload again `hironx_gripper_model.png` at http://wiki.ros.org/action/AttachFile/rtmros_nextage/Tutorials/Changing%20Nextage%20Grippers%20in%20Robot%20Model?action=AttachFile? It got deleted when you moved the wiki page

**Comment by emijah** [comment]
Sorry I'm still working on the model. I have VRML files of the parts but
for some reason I can't import them.

2014-02-03 Isaac Isao Saito notifications@github.com:

**Comment by k-okada** [comment]
@130 I had attached the gripper model png file.

**Comment by 130s** [comment]
@k-okada > I had attached the gripper model png file.

Arigatou gozaimasu.

Do you use editor to modify wiki? [Your last change](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Changing%20Nextage%20Grippers%20in%20Robot%20Model?action=diff&rev2=24&rev1=23) stopped the `CodeRef` macro (that needs new line feed when defining `block`). I've already fixed in the latest commit.

**Comment by k-okada** [comment]
I used GUI interface, sorry if I broke documents.

**Comment by 130s** [comment]
I see, that issue is now reported (as referenced)

**Comment by 130s** [comment]
Done. http://wiki.ros.org/rtmros_nextage/Tutorials
Improvements can be directly applied on the wiki page. Also anyone interested in updates made on wiki should subscribe each tutorial page.
