### ISSUE TITLE
IKFast plugin: Minor fix to apply

### ISSUE THREAD

**Issue by ghost** [tork-a/rtmros_nextage#341]
Hi all,

I am reporting a minor bug about the harmonize function inside the two next files (line 482, indigo-devel branch):
- rtmros_nextage/nextage_ik_plugin/src/nextage_left_arm_ikfast_moveit_plugin.cpp 
- rtmros_nextage/nextage_ik_plugin/src/nextage_right_arm_ikfast_moveit_plugin.cpp

A minus sign is missing in order to properly bound the angles in [-2*PI; 2*PI]
line 482: `while(solution[i] < -2*M_PI) { ...`

Regards,
Yoann.

**Comment by 130s** [comment]
Thanks for the headsup. A few questions:
- Have you confirmed the suggested change works? On simulator or on the real robot? 
- Do you think you can open a pull request?

Either way I'd like to ask @k-okada for taking care of this.

**Comment by 130s** [comment]
Either way I'd like to ask @k-okada for taking care of this.

**Comment by ghost** [comment]
Hi 130s,

It was tested with the simulator and it works.
I have created the pull request: #342 

Regards,
Yoann.

**Comment by 130s** [comment]
Thanks!
Continued in #342
