### ISSUE TITLE
Define how to manage robot's serial number

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#37]
When you need to work with multiple robots of the same or slightly different model, it's so important to be able to tell the version of software installed per each robot. This is crucial particularly for the robots like NEXTAGE OPEN that runs on `QNX` where package management system is not used to manage the version number of robot components.

One way done at jsk lab I heard is to use environment variable like this:

```
$ export ROBOT=H7
$ make ROBOT=H7
```

(In this case then does the `Makefile` describe all different conditions per robots?)

**Comment by 130s** [comment]
From the recent conversation with the manufacturer, I conclude myself that this isn't feasible (because they are willing to make the serial number accessible to anyone other than the purchaser).

**Comment by 130s** [comment]
They are _not_.

**Comment by k-okada** [comment]
even if they do not provide serial number, we may have to create minor modification for each robot, for example robot with force sensors, etc....

```
$ make ROBOT=H7
``
invoke `gcc -O -DROBOT=${ROBOT}" and used in sourced for #ifdef H7 ... etc
```
