### ISSUE TITLE
Self collision detection for Hiro-NXOpen robots

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#47]
Sounds like a common requirement for the robot client. Especially there are two "modes" (`hrpsys`, ``MoveIt!`), solution may involve design restructuring.

Ideas, and pros and cons per each are such.  Both ideas needs extensive tests.:
- Integrate `MoveIt!` with all methods in [HIRONX](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html)
  - \+ The more MoveIt! grows the better collision detection we get.
  - \- Robot-client class `HIRONX` needs to be re-written. Even existing well-tested methods need to be re-tested.
  - \- No control over trajectory (MoveIt! does this instead of hrpsys).
- Use a [collision visualization](https://code.google.com/p/rtm-ros-robotics/issues/detail?id=249) based on `hrpsys`' [CollisionDetector](http://code.google.com/p/hrpsys-base/source/browse/trunk/rtc/CollisionDetector).
  - \+ can be used to detect collision to turn off servos
  - \- Only detects interference.

I would ask @k-okada for the decision.

**Comment by 130s** [comment]
I suggest to add self collision feature asap and that will be a good update for [the milestone to release ver 0.3.0](https://github.com/tork-a/rtmros_nextage/issues/milestones).

**Comment by k-okada** [comment]
I asked this task to miyake-kun(@kenji0919 )[1] last week, but not sure about current status. If he is busy, someone can take over this job.
I would suggest starting from visualization and add a code just to servo off if collision is detected. Thus should be done with in 10 lines of codes. and you can confirm what's going on with visualization.

As for pros and cons, each approach needs extensive tests and even if we have extensive tests, model error and difference of hand modules will fail to detect collisions, so there are no perfect solutions. If you add large margins  (padding) it seems ok, but as users using the robot, they want to reduce padding (smaller margins) and hit the robot.

[1] https://github.com/start-jsk/rtmros_hironx/issues/36.

**Comment by 130s** [comment]
Closing; escating this to the upstream repo (hironx). Ideas suggested here are ticketed:
- https://github.com/start-jsk/rtmros_hironx/issues/36
- https://github.com/start-jsk/rtmros_hironx/issues/90
