### ISSUE TITLE
Add stereo camera module

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#5]

**Comment by 130s** [comment]
There are at least 4 ROS packages that handle `uEye` now, and [somebody is interested in incorporating those](http://lists.ros.org/pipermail/ros-users/2013-November/068056.html). We can ask him to release as ROS deb, or we can take that part depending on workload.

**Comment by 130s** [comment]
[Discussion among ROS users restarted](http://lists.ros.org/pipermail/ros-users/2014-February/068255.html) randomly. fyi @emijah

**Comment by 130s** [comment]
This might be a good subject for hackathon?

**Comment by k-okada** [comment]
might be...

But may be too difficult for student if you want to use developed software as a released software, because you need to take care about error handling and initilization/termination in the code.S Some expert have to take care and finalize them

**Comment by emijah** [comment]
In that case it may be a good subject for an intern.
Do you think it would be possible to joint host an intern?

2014-05-06 1:52 GMT+09:00 Kei Okada notifications@github.com:

**Comment by 130s** [comment]
I took over [this task](https://bitbucket.org/kmhallen/ueye/issue/7/merge-features-from-other-ueye-related-ros#comment-10258212).

**Comment by emijah** [comment]
Great!

**Comment by 130s** [comment]
Not sure how much/less this is related but there's a `GSoC` project proposal http://wiki.osrfoundation.org/gsoc14

```
Improved Industrial Camera Support

    List of prerequisites: Linux, Git, familiarity with ROS, OpenCV
    Description of programming skills: C++ Python
    Difficulty level: Medium
    List of potential mentors: Katherine Scott
    Detailed description: Professional machine vision cameras are often used in industrial applications like pick and place, metrology, and quality control. The support for these types of cameras in ROS is not as great as it could be. For this project the student will create new ROS nodes to support a variety of common machine vision camera vendors. Furthermore many of these vendors now offer cameras that see in different parts of the spectrum, such as long wave and near wave infrared. The student may also opt to build tools to help integrate these kinds of cameras into ROS. 
```

I don't find this in GSoC as approved. [Asked the mentor listed](https://twitter.com/130s/status/469659852478746625).

**Comment by 130s** [comment]
I think we delegate this to #103
