### ISSUE TITLE
Different reference frames b/w hironx and nxopen

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#51]
Because of the base added to the model of `NEXTAGE OPEN`, it's height is different from that of `Hironx`. This causes an issue eg. when using a same program that works with `hironx` that passes an absolute pose to methods like `setTargetPose`.

A suggested simple solution would be to change those methods that cause issues to accept ref frame, in either `hrpsys` level or in client (`NextageClient`).

**Comment by 130s** [comment]
I mean issues occur when using the same program with hironx. I updated the original description.

**Comment by 130s** [comment]
> A suggested simple solution would be to change those methods that cause issues to accept ref frame, in either hrpsys level or in client (NextageClient).

[Patch added to hrpsys](https://code.google.com/p/hrpsys-base/issues/detail?id=184).

But now, as one of the core users says, even with this patch, exactly the same client program cannot be used for both robots; for either robot you have to specify the reference frame.

**Comment by 130s** [comment]
Suggestion; with the following, we could work this issue around without changing model nor client program.
- No change to [hironx_client.Hironx](https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py).
- In [nextage_client.NextageClient](https://github.com/tork-a/rtmros_nextage/blob/groovy-devel/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.py), override `setTargePose` with setting the arg `ref_frame_name` as `odom` (or whatever that points to the bottom of this robot's base).

Application developers can just use methods from the classes above without changing models and paying attention to the frame referred.

Any drawback with thjs?

**Comment by k-okada** [comment]
+1, but you must be very careful when we hrpsys 315.2.0 is out.

**Comment by 130s** [comment]
We can try setting versions of the dependency in package.xml
http://www.ros.org/reps/rep-0127.html#various once the new version of
`hrpsys` is out.

**Comment by k-okada** [comment]
> <build_depend version_gte="1.1" version_lt="2.0">genmsg</build_depend>

does this means my_package depends on genmsg of version 1.1-2.0? or
version 1.1-2.0 of my_package depends on genmsg?

**Comment by 130s** [comment]
Not sure but I assume the former.

Now I'm trying this versioned `build_depend` feature but it's not working for me. [Asked here](http://answers.ros.org/question/136526/how-versioned-build_depend-works/).

**Comment by 130s** [comment]
Once https://github.com/start-jsk/rtmros_hironx/pull/298 gets merged, we'll have ways to specify the reference frame for get and set pose/position/rotation methods, and therefore this ticket can be closed then .

**Comment by 130s** [comment]
Closing since https://github.com/start-jsk/rtmros_hironx/pull/298 is merged.
