### ISSUE TITLE
Enable/document impedance control

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#52]
Since it's been done on `HRP2` and `Schaft` robots via `hrpsys`, we may just have to adjust it to Hiro/Nextage (if necessary), or we may just even document how to enable it.

**Comment by k-okada** [comment]
controller itself is tested, but sensor driver for hiro/nextage hardware  is missing. some one need to write them. I'm not sure but we may start from `http://www.nitta.co.jp/?post_type=sensor&p=4378` this sample program.

**Comment by k-okada** [comment]
@hyaguchijsk, please write documents if you have confirmed it is working. @130s will show you where/how to write them.

**Comment by 130s** [comment]
How about http://wiki.ros.org/rtmros_nextage/Tutorials/Adding%20feedback%20control

**Comment by 130s** [comment]
Thanks to @hyaguchijsk a progress is made https://github.com/start-jsk/rtmros_hironx/pull/253
