### ISSUE TITLE
Errors on ROS wiki documents

### ISSUE THREAD

**Issue by hyaguchijsk** [tork-a/rtmros_nextage#59]
Hi all,

I found some errors on ROS wiki documentation while I installed.

1.

According to
http://wiki.ros.org/rtmros_nextage/Tutorials/Install%20NEXTAGE%20OPEN%20software%20on%20your%20machine
I installed via debian binary (in section 4).

then according to
http://wiki.ros.org/rtmros_nextage

```
$ source `rospack find openrtm_tools`/scripts/rtshell-setup.sh
```

and I got following errors.

```
[rospack] Error: stack/package rtctree not found
[rospack] Error: stack/package rtsprofile not found
```

I think it requires rtshell-core.

```
sudo apt-get install ros-hydro-rtshell-core
```

2.
According to
http://wiki.ros.org/rtmros_nextage
I tried to run 

```
$ roslaunch hironx_moveit_config moveit_planning_execution.launch
```

then there are no hironx_moveit_config package,
instead of this I found nextage_moveit_config.

```
$ roslaunch nextage_moveit_config moveit_planning_execution.launch
```

seems correct command.

regards,

**Comment by k-okada** [comment]
Did you try with shadow-fixed repository?
rtshell should depends on rtctree and rtsprofile.
https://github.com/start-jsk/rtshell_core/blob/master/rtshell/package.xml

**Comment by hyaguchijsk** [comment]
I tried to purge all packages and reinstall from shadow-fixed repository,
then the first error is corrected, thanks.

How about the second problem?

**Comment by 130s** [comment]
For the 2nd issue, your guess should be correct. I'll fix the wiki once
I'll be back to my computer.

**Comment by 130s** [comment]
Fixed via http://wiki.ros.org/action/info/rtmros_nextage?action=diff&rev2=23&rev1=22. Thank you @hyaguchijsk
