### ISSUE TITLE
Port to ROS Hydro

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#6]

**Comment by k-okada** [comment]
see https://code.google.com/p/rtm-ros-robotics/issues/detail?id=204 for progress

**Comment by 130s** [comment]
binary 0.2.3 is built and available in `shadow-fix` repo. Together with [this ticket](https://github.com/start-jsk/hironx-package/issues/55) I'll test runtime.

**Comment by 130s** [comment]
Hydro version is released
