### ISSUE TITLE
Extract common part from hironx

### ISSUE THREAD

**Issue by k-okada** [tork-a/rtmros_nextage#7]
[ここ](https://bitbucket.org/tork-a/iros13/issue/61/hiro-nextage)からの移譲．

hironxとコードが被らないようにしたいです．

また，
#2 , #3 などの一部は

http://rtm-ros-robotics.googlecode.com/svn/trunk/rtmros_hironx/hironx_ros_bridge/test/
でトライされています．

nextage_description, 
hironx_description
さえあれば，あとは共通のコード（特にCMake周りか？）で動くようになっている，というのがベストでしょうか．

また，一部にhironxとnextageで微妙にファイル名が違うのも揃えておきたい所ではあります．
- [x] script/nextage_client_standalone.py vs script/hironx.py, 
- [x] src/nextage_client.py vs src/hironx.py, 
- [x] moveit_planning_exec.launch vs  moveit_planning_execution.launch

**Comment by 130s** [comment]
Moved to http://code.google.com/p/rtm-ros-robotics/issues/detail?id=291
