### ISSUE TITLE
(nextage_ros_bridge) Add dependency on rtshell

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#72]
Looks like `rtshell` doesn't get installed automatically upon installing `nextage_ros_bridge`. Because of `rtmlaunch` command simulation uses I think it's nicer to add `run_depend` (in `package.xml` format 1. `depend` in format 2).

**Comment by k-okada** [comment]
https://github.com/start-jsk/rtmros_common/blob/master/openrtm_tools/package.xml

openrtm_tools depends on rtshell, so I think what we need is depend hrpsys_ros_bridge depends on openrtm_tools

**Comment by 130s** [comment]
Closing; I was wrong, `openrtm_tools` gets installed via `nextage_ros_bridge` 0.2.13. 
![rdepend_openrtm_tools](https://cloud.githubusercontent.com/assets/1840401/3278106/8c0b1c72-f3a6-11e3-94ed-f6f5f0470e4e.png)

(I must have taken something wrong when I was talking to a user who said he installs `rtshell-core` along with `rtmros_nextage`.)
