### ISSUE TITLE
Missing tutorial for chaging grippers

### ISSUE THREAD

**Issue by k-okada** [tork-a/rtmros_nextage#76]
I noticed that http://wiki.ros.org/rtmros_nextage/Tutorials/Changing%20Grippers%20on%20Nextage%20Hardware page is blank, Is this page is no-longer used? or something wrong on wiki format?

**Comment by 130s** [comment]
That tutorial page is there, expecting someone in the community to fill in. I [added call-for-volunteer](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Changing%20Grippers%20on%20Nextage%20Hardware?action=diff&rev2=4&rev1=3). I personally don't have an experience yet in doing that.

**Comment by k-okada** [comment]
I see. @emijah may have that experience.

**Comment by emijah** [comment]
@130s How do you respond?

**Comment by 130s** [comment]
If anyone is interested in documenting about this (so appreciated!), please go to the tutorial web page (cited below), you may need to create your account, then edit the wiki however necessary. Notice that it's wiki so everyone on the internet has right to edit (your edition might sometime get modified by someone else).

http://wiki.ros.org/rtmros_nextage/Tutorials/Changing%20Grippers%20on%20Nextage%20Hardware
