### ISSUE TITLE
robot.goInitial fails with "AttributeError: class HIRONX has no attribute 'INITPOS_TYPE_EVEN'"

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#78]
Can happen only with v0.2.14 with `hironx_ros_bridge` LTE 1.0.14, of which new version needs to include [this commit](https://github.com/start-jsk/rtmros_hironx/commit/b7961b99e80da825d315833d96ea2dd108bd8d3d).

_How to apply tentative patch_
1.  On Ubuntu, run:
   
   ```
   $ cd /opt/ros/hydro/lib/python2.7/dist-packages/hironx_ros_bridge/
   $ sudo cp hironx_client.py hironx_client.py.org
   ```
2. Replace content of `hironx_client.py` with https://raw.githubusercontent.com/start-jsk/rtmros_hironx/b7961b99e80da825d315833d96ea2dd108bd8d3d/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py

This tentative patch can be automatically removed when you install newer version of `hironx_ros_bridge` via apt.

**Comment by 130s** [comment]
Requires https://github.com/start-jsk/rtmros_hironx/issues/117 addressed.

**Comment by k-okada** [comment]
this should be checked in https://travis-ci.org/tork-a/rtmros_nextage, can
you look into it ? or should I do that.

**Comment by 130s** [comment]
travis config of this repository doesn't test anything (my bad...I haven't added one). I'm working on this.

**Comment by 130s** [comment]
> travis config of this repository doesn't test anything (my bad...I haven't added one). I'm working on this.

Done in #92.
