### ISSUE TITLE
ModelLoaderException : /opt/ros/hydro/share/nextage_description/models/main.wrl cannot be found.

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#79]
On new installed machine, `ModelLoaderException` repeats in a very fast loop.

```
$ roslaunch nextage_ros_bridge nextage_ros_bridge.launch nameserver:=nextage &> roslaunch_bridge.log
:
ModelLoaderException : /opt/ros/hydro/share/nextage_description/models/main.wrl cannot be found.
[HrpsysJointTrajectoryBridge] failed to load model[]
ModelLoaderException : /opt/ros/hydro/share/nextage_description/models/main.wrl cannot be found.
:
ModelLoaderException : /opt/ros/hydro/share/nextage_description/models/main.wrl cannot be found.
[ERROR] [1404979055.697524972]: Target Node visual1/node_joint0_axis0 NOT found!!!
[rtmlaunch] starting...  /opt/ros/hydro/share/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
ModelLoaderException : /opt/ros/hydro/share/nextage_description/models/main.wrl cannot be found.
ModelLoaderException : /opt/ros/hydro/share/nextage_description/models/main.wrl cannot be found.
[rtmlaunch] RTCTREE_NAMESERVERS nextage:15005 nextage:15005
[rtmlaunch] SIMULATOR_NAME RobotHardware0
[rtmlaunch] check connection/activation
:
[ INFO] [1404979056.045774554]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0

SUMMARY
========

PARAMETERS
 * /collision_state/comp_name
 * /controller_configuration
 * /diagnostic_aggregator/analyzers/computers/contains
 * /diagnostic_aggregator/analyzers/computers/path
 * /diagnostic_aggregator/analyzers/computers/type
 * /diagnostic_aggregator/analyzers/hrpsys/contains
 * /diagnostic_aggregator/analyzers/hrpsys/path
 * /diagnostic_aggregator/analyzers/hrpsys/type
 * /diagnostic_aggregator/analyzers/mode/contains
 * /diagnostic_aggregator/analyzers/mode/path
 * /diagnostic_aggregator/analyzers/mode/type
 * /diagnostic_aggregator/analyzers/motor/contains
 * /diagnostic_aggregator/analyzers/motor/path
 * /diagnostic_aggregator/analyzers/motor/type
 * /diagnostic_aggregator/base_path
 * /diagnostic_aggregator/pub_rate
 * /robot_description
 * /rosdistro
 * /rosversion

NODES
  /
    CollisionDetectorComp (hrpsys/CollisionDetectorComp)
    DataLoggerServiceROSBridge (hrpsys_ros_bridge/DataLoggerServiceROSBridgeComp)
:

$ ls -lath /opt/ros/hydro/share/nextage_description/models/main.wrl
-rw-r--r-- 1 root root 25K Jun 20 19:10 /opt/ros/hydro/share/nextage_description/models/main.wrl
```

```
$ dpkg -p ros-hydro-nextage-description|grep Ver
Version: 0.2.14-0precise-20140621-0805-+0000
$ dpkg -p ros-hydro-nextage-ros-bridge|grep Ver
Version: 0.2.14-0precise-20140623-0906-+0000
$ dpkg -p ros-hydro-hironx-ros-bridge|grep Ver
Version: 1.0.16-1precise-20140708-0336-+0000
$ dpkg -p ros-hydro-openhrp3|grep Ver
Version: 3.1.5-6precise-20140617-0805-+0000
$ dpkg -p ros-hydro-hrpsys|grep Ver
Version: 315.2.2-0precise-20140617-1729-+0000
```

**Comment by k-okada** [comment]
> $ roslaunch nextage_ros_bridge nextage_ros_bridge.launch
> nameserver:=nextage

wrlは体内のnameserverから呼び出されるから，モデルの場所をそうつたえないとだめじゃないでしょうか．

**Comment by k-okada** [comment]
https://github.com/tork-a/rtmros_nextage/blob/hydro-devel/nextage_ros_bridge/launch/nextage_ros_bridge.launch
の
 <arg name="MODEL_FILE" default="$(find nextage_description)/models/main.wrl" />
の部分ですね．

2014-07-10 17:21 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:

> > $ roslaunch nextage_ros_bridge nextage_ros_bridge.launch
> > nameserver:=nextage
> 
> wrlは体内のnameserverから呼び出されるから，モデルの場所をそうつたえないとだめじゃないでしょうか．

**Comment by k-okada** [comment]
$ roslaunch nextage_ros_bridge nextage_ros_bridge.launch
nameserver:=nextage MODEL_FILE:=/opt/jsk/HIRO/model/main.wrl

2014-07-10 17:22 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:

> https://github.com/tork-a/rtmros_nextage/blob/hydro-devel/nextage_ros_bridge/launch/nextage_ros_bridge.launch
> の
>  <arg name="MODEL_FILE" default="$(find nextage_description)/models/main.wrl" />
> の部分ですね．
> 
> 2014-07-10 17:21 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:
> 
> > > $ roslaunch nextage_ros_bridge nextage_ros_bridge.launch
> > > nameserver:=nextage
> > 
> > wrlは体内のnameserverから呼び出されるから，モデルの場所をそうつたえないとだめじゃないでしょうか．

**Comment by k-okada** [comment]
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/launch/hironx_ros_bridge_real.launch
が参考になるでしょうか

2014-07-10 17:22 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:

> $ roslaunch nextage_ros_bridge nextage_ros_bridge.launch
> nameserver:=nextage MODEL_FILE:=/opt/jsk/HIRO/model/main.wrl
> 
> 2014-07-10 17:22 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:
> 
> > https://github.com/tork-a/rtmros_nextage/blob/hydro-devel/nextage_ros_bridge/launch/nextage_ros_bridge.launch
> > の
> >  <arg name="MODEL_FILE" default="$(find nextage_description)/models/main.wrl" />
> > の部分ですね．
> > 
> > 2014-07-10 17:21 GMT+09:00 Kei Okada k-okada@jsk.t.u-tokyo.ac.jp:
> > 
> > > > $ roslaunch nextage_ros_bridge nextage_ros_bridge.launch
> > > > nameserver:=nextage
> > > 
> > > wrlは体内のnameserverから呼び出されるから，モデルの場所をそうつたえないとだめじゃないでしょうか．

**Comment by 130s** [comment]
Thank you, `$ roslaunch nextage_ros_bridge nextage_ros_bridge.launch nameserver:=nextage MODEL_FILE:=/opt/jsk/etc/HIRONX/model/main.wrl` fixed the issue, though I never had to specify the model location. Not sure maybe the [recent change in installing model file](https://github.com/start-jsk/rtmros_hironx/blob/f3e04bcd438b25d75bdbf0b55ce165e797e08105/hironx_ros_bridge/robot/robot-compile-setup.sh#L42) is related. 
Open until permanent fix will be applied.

**Comment by k-okada** [comment]
due to https://github.com/start-jsk/rtmros_hironx/commit/bb0672be3e03e5366e03fe50520e215302b8419f#diff-fcc785cbbe7f734d6750d5bf43e26df6

**Comment by snozawa** [comment]
関連する情報を共有しておきます。
現状カメラのTFは、HrpsysSeqStateROSBridgeImpl.cppの中で
ModelLoaderから取得してだしています。
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/HrpsysSeqStateROSBridgeImpl.cpp#L133

なので、カメラのオフセットなど情報を更新する場合は、
体内のモデルを更新してModelLoaderをあげなおす必要がありました。

**Comment by 130s** [comment]
https://github.com/tork-a/rtmros_nextage/pull/81 addresses this issue and allows users to not type in any argument by default. 
Thank you for the comments.

**Comment by k-okada** [comment]
You have to use rtmlaunch, not roslaunch
