### ISSUE TITLE
Enable nextage_client_standalone to connect to remote host

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#8]
Currently it only connects to ros_bridge node running locally, which is very inconvenient when working with real robots.

**Comment by k-okada** [comment]
./hironx.py --host remote.host should work as described in the last line of the code

see https://code.google.com/p/rtm-ros-robotics/source/browse/trunk/rtmros_hironx/hironx_ros_bridge/scripts/hironx.py

**Comment by 130s** [comment]
This has been enabled for awhile, and it's even [documented in the tutorial](http://wiki.ros.org/rtmros_nextage/Tutorials/Operating%20Hiro%2C%20NEXTAGE%20OPEN%20from%20Client%20Pograms#Working_with_a_real_robot) for awhile.
