### ISSUE TITLE
Add DIO pin checker

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#94]
From https://github.com/tork-a/rtmros_nextage/pull/93

TODOs:
- [x] Add tests for checking if digital IO work accordingly as in the spec.
- [x] Dismiss these tests on CI tools (jenkins, travis etc.) Because all the tests added in PReq require hardware, these tests become ERROR.

**Comment by k-okada** [comment]
> Dismiss these tests on CI tools

IO related code should run on simulation, although readIO just returns writeIO data. Please let me know if you create test code for DIO.

**Comment by 130s** [comment]
Ah I've added them...Is there a way to bypass them on CI tests?

**Comment by k-okada** [comment]
Created patch https://github.com/fkanehiro/hrpsys-base/pull/273, that just ignore read/write dio on simulation mode, once this patch has accepted, CI error will gone

**Comment by 130s** [comment]
Thank you for https://github.com/fkanehiro/hrpsys-base/pull/273 that [seems to be working for travis build](https://travis-ci.org/tork-a/rtmros_nextage/jobs/31413508). `*handlight*` methods still need to be taken care of. They are in NXO level (not in `hrpsys`). I'll work on it.
