### ISSUE TITLE
hironx_moveit_config does not get installed with nextage_moveit_config

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#96]
With nextage_moveit_config 0.2.15, `hironx_moveit_config` is `run_depend` but it doesn't get installed via apt. Is `run_depend` not counted as dependency in Ubuntu?

**Comment by k-okada** [comment]
https://github.com/tork-a/rtmros_nextage/blob/0.2.15/nextage_moveit_config/package.xml

2.15 does not have run_depend to hironx

**Comment by 130s** [comment]
Ahh, that makes the most sense!
