### ISSUE TITLE
Either only Natto-view or Interactive Marker appears

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#97]
With version 0.2.15.

Depending on the chosen `Fixed Frame`, only either one appears:
- `WAIST`: `natto-view`
- `WAIST_Link`: `Interactive Marker`

NXO nor Hironx intend to publish `WAIST_Link` so it must be published somewhere upstream.

**Comment by k-okada** [comment]
could you check frame by `rosrun tf view_frames` ?
