### ISSUE TITLE
(MoveIt!) To modify joint_limit velocity and acceleration values on the fly

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#98]
The [current values](https://github.com/tork-a/rtmros_nextage/commit/bbf7d31e285223ac216f5d11da8ca4249947ebaa#diff-ff83b48fa6274dda265e036bf5a75a9e) are felt sometimes too fast. But the only way to change it AFAIK is to modify the file `/opt/ros/hydro/share/nextage_moveit_config/config/joint_limits.yaml` in the protected directory, which is not recommended.

Being able to pass those values as `roslaunch` argument might be a good solution.

**Comment by k-okada** [comment]
Changing joint speed is also required by @wyasuda, he asked mailing list and got some feed back I think

**Comment by wyasuda** [comment]
I asked questions here.
https://groups.google.com/forum/#!topic/moveit-users/CCj9Tam2jiw
Still I could not get answers about speed control.

I found another topic about speed control below.
https://groups.google.com/forum/#!searchin/moveit-users/speed/moveit-users/7n45S8DUjys/xIM24szuetEJ

**Comment by 130s** [comment]
> https://groups.google.com/forum/#!topic/moveit-users/CCj9Tam2jiw
> Still I could not get answers about speed control.
> 
> I found another topic about speed control below.
> https://groups.google.com/forum/#!searchin/moveit-users/speed/moveit-users/7n45S8DUjys/xIM24szuetEJ

Good to know these, and looks like there's another one here that opened up an enhancement request: https://github.com/ros-planning/moveit_ros/issues/368

And I conclude that there hasn't been an official MoveIt! feature to dynamically set velocity. Closing for now.

**_Users**_
For statically changing velocity per execution, edit the following file accordingly (the default is set with moderately slow value).

```
`rospack find nextage_moveit_config`/config/joint_limits.yaml
```
